---
title: "Compare Scenarios 2"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
    toc: yes
    number_sections: yes
    toc_depth: 6
    keep_tex: false
    template: cs2_latex_template.tex
    includes: 
      in_header: cs2_pdf_header_include.tex
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 6
    number_sections: yes
geometry: "a4paper,landscape,left=0.5cm,right=0.5cm,top=0.5cm,bottom=0.5cm,footnotesep=0.0cm,footskip=0.1cm"
params:
  mifScen: ""
  mifScenNames: null
  cfgScen: null
  cfgDefault: null
  mifHist: ""
  yearsScen: !r c(seq(2005, 2060, 5), seq(2070, 2100, 10))
  yearsHist: !r c(seq(1960, 2020, 1), seq(2025, 2100, 5))
  yearsBarPlot: !r c(2010, 2030, 2050, 2100)
  yearRef: 2020
  reg: null
  modelsHistExclude: !r c()
  sections: "all"
  userSectionPath: null
  mainReg: "World"
  figWidth: 15 
  figHeight: 10
  warning: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = FALSE,
  warning = params$warning,
  fig.width = params$figWidth,
  fig.height = params$figHeight)
```


```{r fix interactive plot size}
# Hack to use the same fig.width and fig.height as described in previous chunk
# for chunks in RStudio Notebook mode.
if (interactive()) {
  insertExprAtStartOfFun <- function(fun, funName, env, expr) {
    body(env[[funName]]) <- call("{", expr, body(fun))
  }
  fn <- ".rs.setNotebookGraphicsOption"
  envToolsRstudio <- as.environment("tools:rstudio")
  if (!exists(".old.rs.setNotebookGraphicsOption"))
    oldRsSetNotebookGraphicsOption <- envToolsRstudio[[fn]]
  insertExprAtStartOfFun(
    oldRsSetNotebookGraphicsOption,
    fn,
    envToolsRstudio,
    rlang::expr({
      width <- !!knitr::opts_chunk$get()$fig.width
      height <- !!knitr::opts_chunk$get()$fig.height
      units <- "in"
    })
  )
}
```


```{r libraries, include=FALSE}
# kableExtra must not be loaded before the call of library(kableExtra) below,
# as its .onLoad() function must be called to tell knitr about add necessary
# LaTeX libraries needed for tables.
# If the following line is not included, successive calls to compareScenarios2()
# may cause "Undefined control sequence" errors in LaTeX.
try(unloadNamespace("kableExtra"), silent = TRUE)

library(gridExtra) # nolint
options(tidyverse.quiet = TRUE) # nolint
library(tidyverse) # nolint
library(kableExtra) # nolint
library(quitte) # nolint
library(mip) # nolint
library(remind2) # nolint
```


```{r read config files}
if (!is.null(params$cfgScen)) {
  loadCfg <- function(path) {
    env <- new.env()
    load(path, envir = env)
    return(env$cfg)
  }
  cfgs <-
    tibble(path = unname(params$cfgScen)) %>%
    rowid_to_column("fileid") %>%
    mutate(cfg = map(path, loadCfg)) %>%
    unnest(cfg) %>%
    mutate(
      name = names(cfg),
      value = unname(cfg),
      cfg = NULL)
  cfgGms <-
    cfgs %>%
    filter(name == "gms") %>%
    unnest(value) %>%
    mutate(name = names(value))
  cfgTopLevel <-
    cfgs %>%
    filter(name != "gms")
  rm(cfgs)
}
if (!is.null(params$cfgDefault)) {
  env <- new.env()
  source(params$cfgDefault, local = env, echo = FALSE) # nolint
  cfgDefault <- env$cfg
}
```


```{r read scenario mifs}
# Read *.mif-files as nested tibble.
dataScenNested <-
  tibble(path = unname(params$mifScen)) %>%
  rowid_to_column("fileid") %>%
  mutate(data = map(
    path,
    read.quitte,
    factors = TRUE,
    # read.quitte() default NA-strings and Inf, -Inf
    na.strings = c("UNDF", "NA", "N/A", "n_a", "Inf", "-Inf"))) %>%
  unnest(data) %>%
  nest(data = -c(fileid, path, scenario))
# Add column character column "newScenarioName",
# either with contents of params$mifScenNames or copy names from column scenario.
if (is.null(params$mifScenNames)) {
  dataScenNested <-
    dataScenNested %>%
    mutate(newScenarioName = as.character(scenario))
} else {
  dataScenNested <-
    dataScenNested %>%
    left_join(
      tibble(
        fileid = seq_along(params$mifScen),
        newScenarioName = params$mifScenNames),
      by = "fileid")
}
# Check for duplicated scenario names.
if (anyDuplicated(dataScenNested$newScenarioName)) {
  warning("There are duplicated scenario names. They will be renamed.")
  dataScenNested <-
    dataScenNested %>%
    mutate(newScenarioName = make.unique(newScenarioName))
}
# Retrieve data for reference table to be shown at the beginning of the document.
fileReference <-
  dataScenNested %>%
  select(fileid, path, scenario, newScenarioName)

# Apply renaming of scenario, unnest, and select only relevant columns.
dataScen <-
  dataScenNested %>%
  mutate(scenario = factor(newScenarioName, levels = newScenarioName)) %>%
  unnest(data) %>%
  select(model, scenario, region, variable, unit, period, value)
```

```{r define scenario colors}
# Get colors of scenarios to be used, e.g., in the info sections.
# They will coincide with the colors of the scenarios in line plots.
scenarioColors <- plotstyle(fileReference$newScenarioName)
lightenColor <- function(clr, by) {
  colRGB <- colorRamp(c(clr, "white"))(by)
  rgb(colRGB[1], colRGB[2], colRGB[3], maxColorValue = 255)
}
bkgndColors <- vapply(scenarioColors, lightenColor, rgb(0, 0, 0), by = 0.5)
```


```{r read historical mif}
dataHist <-
  params$mifHist %>%
  read.quitte(factors = TRUE)
```


```{r preprocess}
# Filter years and NA.
dataScen <-
  dataScen %>%
  filter(period %in% params$yearsScen)
dataHist <-
  dataHist %>%
  filter(period %in% params$yearsHist, !(model %in% params$modelsHistExclude), !is.na(value)) %>%
  droplevels()

# Combine into one data frame and remove old.
data <- bind_rows(dataScen, dataHist)
rm(dataScen, dataScenNested, dataHist)

data <-
  data %>%
  # In the variable names, replace `$dot$` by `.`.
  mutate(
    variable = substituePlaceholder(variable)) %>%
  # In the variable names, replace `|+|`, `|++|`, `|+++|`, ... by `|`.
  mutate(
    varplus = as.character(variable),
    variable = deletePlus(variable))

# Filter regions.
if (!is.null(params$reg)) {
  data <-
    data %>%
    filter(region %in% params$reg) %>%
    droplevels()
}
```


```{r Corrections}
# TODO: Should not be done in compareScenarios.

# Change unit million US$2005/yr to billion US$2005/yr.
# Relevant for ARIADNE historical EUR GDP|PPP.
data <-
  bind_rows(
    data %>% filter(!unit %in% c("million US$2005/yr")),
    data %>%
      filter(unit == "million US$2005/yr") %>%
      mutate(
        unit = "billion US$2005/yr",
        value = value / 1000)
  )
```


```{r reference models for historical}
# Sometimes it is necessary to choose a single model for the historical data,
# e.g., calculating per capita variables. These reference models are defined here.
histRefModel <- c(
  "Population" = "WDI",
  "GDP|PPP pCap" = "James_IMF")
```


```{r calcuate pCap variables}
# For all variables in following table, add a new variable to data with the name
# "OldName pCap". Calculate its value by
#     OldValue * conversionFactor # nolint
# and set its unit to newUnit.
# The new variable "OldName pCap" will be available in the plot sections.
pCapVariables <- tribble(
  ~variable, ~newUnit, ~conversionFactor,
  "GDP|PPP", "kUS$2005", 1e6, # creates "GDP|PPP pCap" which is equal to reported variable "GDP|per capita|PPP"
  "GDP|MER", "kUS$2005", 1e6, # creates "GDP|MER pCap" which is equal to reported variable "GDP|per capita|MER"
  "FE", "GJ/yr", 1e9,
  "FE|CDR", "GJ/yr", 1e9,
  "FE|Transport", "GJ/yr", 1e9,
  "FE|Buildings", "GJ/yr", 1e9,
  "FE|Industry", "GJ/yr", 1e9,
  "FE|Buildings|Heating", "GJ/yr", 1e9,
  "FE|Buildings|Appliances and Light", "GJ/yr", 1e9,
  "FE|Buildings|Cooking and Water", "GJ/yr", 1e9,
  "FE|Buildings|Space Cooling", "GJ/yr", 1e9,
  "FE|Buildings|Space Heating", "GJ/yr", 1e9,
  "ES|Transport|Pass", "km/yr", 1e9,
  "ES|Transport|Pass|Road|LDV", "km/yr", 1e9,
  "ES|Transport|Pass|non-LDV", "km/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|BEV", "km/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|FCEV", "km/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|Gases", "km/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|Hybrid Electric", "km/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|Liquids", "km/yr", 1e9,
  "ES|Transport|Freight", "tkm/yr", 1e9,
  "ES|Transport|Freight|Road|Electric", "tkm/yr", 1e9,
  "ES|Transport|Freight|Road|FCEV", "tkm/yr", 1e9,
  "ES|Transport|Freight|Road|Gases", "tkm/yr", 1e9,
  "ES|Transport|Freight|Road|Liquids", "tkm/yr", 1e9,
  "Emi|GHG", "t CO2eq/yr", 1e6,
  "Emi|GHG|Gross|Energy|Supply|Electricity", "t CO2eq/yr", 1e6,
  "Emi|GHG|Gross|Energy|Supply|Non-electric", "t CO2eq/yr", 1e6,
  "Emi|GHG|Energy|Demand|Transport", "t CO2eq/yr", 1e6,
  "Emi|GHG|Energy|Demand|Buildings", "t CO2eq/yr", 1e6,
  "Emi|GHG|Gross|Energy|Demand|Industry", "t CO2eq/yr", 1e6,
  "Emi|GHG|Industrial Processes", "t CO2eq/yr", 1e6,
  "Emi|GHG|Agriculture", "t CO2eq/yr", 1e6,
  "Emi|GHG|Land-Use Change", "t CO2eq/yr", 1e6,
  "Emi|GHG|Waste", "t CO2eq/yr", 1e6,
  "Emi|CO2|CDR|BECCS", "t CO2eq/yr", 1e6,
  "Emi|CO2|CDR|Industry CCS|Synthetic Fuels", "t CO2eq/yr", 1e6,
  "Emi|CO2|CDR|DACCS", "t CO2eq/yr", 1e6,
  "Emi|CO2|CDR|EW", "t CO2eq/yr", 1e6,
  "Emi|CO2", "t CO2eq/yr", 1e6,
  "Emi|CO2|Land-Use Change", "t CO2eq/yr", 1e6,
  "Emi|CO2|Industrial Processes", "t CO2eq/yr", 1e6,
  "Emi|CO2|Energy|Demand|Transport", "t CO2eq/yr", 1e6,
  "Emi|CO2|Gross|Energy|Demand|Industry", "t CO2eq/yr", 1e6,
  "Emi|CO2|Energy|Demand|Buildings", "t CO2eq/yr", 1e6,
  "Emi|CO2|Gross|Energy|Supply|Non-electric", "t CO2eq/yr", 1e6,
  "Emi|CO2|Gross|Energy|Supply|Electricity", "t CO2eq/yr", 1e6)

dataPop <-
  data %>%
  filter(variable == "Population") %>%
  filter(scenario != "historical" | model == histRefModel["Population"]) %>%
  select(scenario, region, period, value) %>%
  mutate(
    population = value * 1e6, # unit originally is million, now is 1
    value = NULL)

dataPCap <-
  data %>%
  inner_join(pCapVariables, "variable") %>%
  left_join(dataPop, c("scenario", "region", "period")) %>%
  mutate(
    value = value / population * conversionFactor,
    variable = paste0(variable, " pCap"),
    varplus = paste0(varplus, " pCap"),
    unit = newUnit,
    newUnit = NULL, conversionFactor = NULL, population = NULL)

data <-
  data %>%
  bind_rows(dataPCap)
```


```{r calcuate pGDP variables}
dataGDP <-
  data %>%
  filter(variable == "GDP|PPP pCap") %>%
  filter(scenario != "historical" | model == histRefModel["GDP|PPP pCap"]) %>%
  select(scenario, region, period, value) %>%
  rename(gdp = value)

# For all variables in following table, add a new variable to data with the name
# "OldName pGDP". Calculate its value by
#     OldValue / (GDP|PPP pCap) * conversionFactor
# and set its unit to newUnit.
# The new variable "OldName pGDP" will be available in the plot sections.
pGdpVariables <- tribble(
  ~variable, ~newUnit, ~conversionFactor,
  "FE", "MJ/US$2005", 1e3,
  "FE|CDR", "MJ/US$2005", 1e3,
  "FE|Transport", "MJ/US$2005", 1e3,
  "FE|Buildings", "MJ/US$2005", 1e3,
  "FE|Industry", "MJ/US$2005", 1e3)

dataPGdp <-
  data %>%
  inner_join(pGdpVariables, "variable") %>%
  left_join(dataGDP, c("scenario", "region", "period")) %>%
  mutate(
    value = value / gdp * conversionFactor,
    variable = paste0(variable, " pGDP"),
    varplus = paste0(varplus, " pGDP"),
    unit = newUnit,
    newUnit = NULL, conversionFactor = NULL, gdp = NULL)

data <-
  data %>%
  bind_rows(dataPGdp)
```


```{r quitte}
data <- as.quitte(data)
```


```{r global variables}
# Set global variables for use in plotting.
options(mip.mainReg = params$mainReg) # nolint
options(mip.yearsBarPlot = params$yearsBarPlot) # nolint
options(mip.histRefModel = histRefModel) # nolint

# Reference year for Kaya decomposition is params$yearRef or the first available year therafter.
options(kaya.refYear = min(params$yearsScen[params$yearsScen >= params$yearRef])) # nolint
```



```{r sectionPaths}
matches <-
  dir() %>%
  str_match("^cs2_([0-9]+).+\\.Rmd$")
availableSections <-
  tibble(
    files = matches[, 1],
    nums = as.numeric(matches[, 2])
  ) %>%
  drop_na() %>%
  arrange(files)
if (length(params$sections) == 1 && params$sections == "all") {
  sectionPaths <- availableSections$files
} else if (is.numeric(params$sections)) {
  sectionPaths <-
    tibble(nums = params$sections) %>%
    left_join(availableSections, by = "nums") %>%
    drop_na() %>%
    pull(files)
} else {
  if (length(params$sections) > 0) {
    sectionPaths <- paste0("cs2_", params$sections, ".Rmd")
  } else {
    sectionPaths <- character(0)
  }
}
```


```{r prepare mark}
# CLICK "RUN ALL CHUNKS ABOVE" HERE TO PREPARE THE ENVIRONMENT
```


```{r include sections, child = sectionPaths}
```


```{r include user section, child = params$userSectionPath}
```
