# Energy Demand

## Final Energy total

```{r}
tot <- "FE"
items <- c(
  "FE|Electricity",
  "FE|Gases",
  "FE|Heat",
  "FE|Solids",
  "FE|Liquids",
  "FE|Hydrogen")
showAreaAndBarPlots(data, items, tot)
showAreaAndBarPlots(data, items, tot, fill=TRUE)
showLinePlots(data, tot)
walk(items, showLinePlots, data=data)
```

## Buildings Final Energy
```{r}
tot <- "FE|Buildings"
items <- c(
  "FE|Buildings|Electricity",
  "FE|Buildings|Gases",
  "FE|Buildings|Heat",
  "FE|Buildings|Solids",
  "FE|Buildings|Liquids",
  "FE|Buildings|Hydrogen")
showAreaAndBarPlots(data, items, tot)
showAreaAndBarPlots(data, items, tot, fill=TRUE)
showLinePlots(data, tot)
walk(items, showLinePlots, data=data)
```


## Industry Final Energy
```{r}
tot <- "FE|Industry"
items <- c(
  "FE|Industry|Electricity",
  "FE|Industry|Gases",
  "FE|Industry|Heat",
  "FE|Industry|Solids",
  "FE|Industry|Liquids",
  "FE|Industry|Hydrogen")
showAreaAndBarPlots(data, items, tot)
showAreaAndBarPlots(data, items, tot, fill=TRUE)
showLinePlots(data, tot)
walk(items, showLinePlots, data=data)
```


### FE mix Steel
```{r}
tot <- "FE|Industry|Steel"
items <- c(
  "FE|Industry|Steel|Heat",
  "FE|Industry|Steel|Hydrogen",
  "FE|Industry|Steel|Solids",
  "FE|Industry|Steel|Liquids",
  "FE|Industry|Steel|Gases",
  "FE|Industry|Steel|Primary|Electricity",
  "FE|Industry|Steel|Secondary|Electricity")
showAreaAndBarPlots(data, items, tot)
```

### FE mix Cement
```{r}
tot <- "FE|Industry|Cement"
items <- c(
  "FE|Industry|Cement|Heat",
  "FE|Industry|Cement|Hydrogen",
  "FE|Industry|Cement|Solids",
  "FE|Industry|Cement|Liquids",
  "FE|Industry|Cement|Gases",
  "FE|Industry|Cement|Electricity")
showAreaAndBarPlots(data, items, tot)
```

### FE mix Non-metallic minerals
```{r}
tot <- "FE|Industry|Non-metallic minerals"
items <- c(
  "FE|Industry|Electricity|Non-metallic minerals",
  "FE|Industry|Gases|Non-metallic minerals",
  "FE|Industry|Heat|Non-metallic minerals",
  "FE|Industry|Hydrogen|Non-metallic minerals",
  "FE|Industry|Liquids|Non-metallic minerals",
  "FE|Industry|Solids|Non-metallic minerals")
showAreaAndBarPlots(data, items, tot)
```

### FE mix Chemicals
```{r}
tot <- "FE|Industry|Chemicals"
items <- c(
  "FE|Industry|Chemicals|Heat",
  "FE|Industry|Chemicals|Hydrogen",
  "FE|Industry|Chemicals|Solids",
  "FE|Industry|Chemicals|Liquids",
  "FE|Industry|Chemicals|Gases",
  "FE|Industry|Chemicals|Electricity|Mechanical work and low-temperature heat",
  "FE|Industry|Chemicals|Electricity|High-temperature heat")
showAreaAndBarPlots(data, items, tot)
```

### FE mix Other Industry
```{r}
tot <- "FE|Industry|Other Industry"
items <- c(
  "FE|Industry|Other Industry|Heat",
  "FE|Industry|Other Industry|Hydrogen",
  "FE|Industry|Other Industry|Solids",
  "FE|Industry|Other Industry|Liquids",
  "FE|Industry|Other Industry|Gases",
  "FE|Industry|Other Industry|Electricity|Mechanical work and low-temperature heat",
  "FE|Industry|Other Industry|Electricity|High-temperature heat")
showAreaAndBarPlots(data, items, tot)
```

### FE|Industry|* line plots
```{r}
showLinePlots(data, "FE|Industry|Steel")
showLinePlots(data, "FE|Industry|Steel|Primary")
showLinePlots(data, "FE|Industry|Steel|Secondary")
showLinePlots(data, "FE|Industry|Cement")
showLinePlots(data, "FE|Industry|Non-metallic minerals")
showLinePlots(data, "FE|Industry|Chemicals")
showLinePlots(data, c("FE|Industry|Other Industry", "FE|Industry|other"))
```

### Specific Energy Consumption

```{r}
items <- c(
  "FE|Industry|Specific Energy Consumption|Cement",
  "FE|Industry|Specific Energy Consumption|Chemicals",
  "FE|Industry|Specific Energy Consumption|Other Industry",
  "FE|Industry|Specific Energy Consumption|Primary Steel",
  "FE|Industry|Specific Energy Consumption|Secondary Steel")
walk(items, showLinePlots, data=data)
```


## Transport Final Energy 
```{r}
tot <- "FE|Transport"
items <- c(
  "FE|Transport|Electricity",
  "FE|Transport|Gases",
  "FE|Transport|Liquids",
  "FE|Transport|Hydrogen")
showAreaAndBarPlots(data, items, tot)
showAreaAndBarPlots(data, items, tot, fill=TRUE)
showLinePlots(data, tot)
walk(items, showLinePlots, data=data)
```

### w/o Bunkers

```{r}
tot <- "FE|Transport|w/o Bunkers"
items <- c(
  "FE|Transport|w/o Bunkers|Electricity",
  "FE|Transport|w/o Bunkers|Gases",
  "FE|Transport|w/o Bunkers|Liquids",
  "FE|Transport|w/o Bunkers|Hydrogen")
showAreaAndBarPlots(data, items, tot)
showLinePlots(data, tot)
walk(items, showLinePlots, data=data)
```

### Transport per type
```{r}
tot <- "FE|Transport"
items <- c(
  "FE|Transport|LDV|Liquids",
  "FE|Transport|LDV|Gases",
  "FE|Transport|LDV|Electricity",
  "FE|Transport|LDV|Hydrogen",
  "FE|Transport|non-LDV|Liquids",
  "FE|Transport|non-LDV|Gases",
  "FE|Transport|non-LDV|Electricity",
  "FE|Transport|non-LDV|Hydrogen")
showAreaAndBarPlots(data, items, tot)
```

### Bunkers

```{r}
tot <- "FE|Transport"
items <- c(
  "FE|Transport|Bunkers",
  "FE|Transport|w/o Bunkers")
showAreaAndBarPlots(data, items, tot)
```
