# Carbon Management

## Carbon Capture

```{r carbon capture}
showLinePlots(data, "Carbon Management|Carbon Capture")
showAreaAndBarPlotsPlus(data, "Carbon Management|Carbon Capture", scales = "fixed")
showAreaAndBarPlotsPlus(data, "Carbon Management|Carbon Capture|Biomass|Pe2Se", scales = "fixed")
showAreaAndBarPlotsPlus(data, "Carbon Management|Carbon Capture|Fossil|Pe2Se", scales = "fixed")

# industry ----
showAreaAndBarPlotsPlus(data,
                        "Carbon Management|Carbon Capture|Industry Energy",
                        scales = "fixed")

showAreaAndBarPlots(
  data = data,
  vars = rev(c('Carbon Management|Carbon Capture|Industry Energy|Cement',
               'Carbon Management|Carbon Capture|Industry Process|Cement',
               'Carbon Management|Carbon Capture|Industry Energy|Chemicals',
               'Carbon Management|Carbon Capture|Industry Energy|Steel')),
  scales = 'fixed',
  orderVars = 'user')
```

## Storage

```{r carbon management storage}
showLinePlots(data, "Carbon Management|Storage")
showAreaAndBarPlotsPlus(data, "Carbon Management|Storage", scales = "fixed")
showAreaAndBarPlotsPlus(data, "Carbon Management|Storage|Industry Energy", scales = "fixed")
showLinePlots(data, "Carbon Management|Storage|Share of annual potential used")
showAreaAndBarPlots(data,
                    vars = c("Carbon Management|Storage"),
                    tot = "Carbon Management|Storage|Maximum annual CO2 storage potential")
```

## Usage

```{r carbon management usage}
showLinePlots(data, "Carbon Management|Usage")
showAreaAndBarPlotsPlus(data, "Carbon Management|Usage", scales = "fixed")
```

## Share

```{r carbon management share}
showLinePlots(data, "Carbon Management|Share of Stored CO2 from Captured CO2")
```

```{r}
showAreaAndBarPlots(data, 
                    vars = c('Carbon Management|Storage',
                             'Carbon Management|Usage'),
                    tot = 'Carbon Management|Carbon Capture')
```

# Materials

## Total plastics production
```{r }
showLinePlots(data, "Carbon Management|Materials|Plastics")
```

## Plastics production by origin
```{r }
showAreaAndBarPlots(data, 
                        vars = c("Carbon Management|Materials|Plastics|Fossil",
                                 "Carbon Management|Materials|Plastics|Biomass",
                                 "Carbon Management|Materials|Plastics|Synfuels"), 
                        scales = "fixed")
```

## Plastics production by fate
```{r }
showAreaAndBarPlots(data, 
                        vars = c("Carbon Management|Materials|Plastics|Incineration",
                                 "Carbon Management|Materials|Plastics|Other destination"), 
                        scales = "fixed")
```
