# Energy Services and Products

## FE|Buildings
```{r}
tot <- "FE|Buildings"
items <- c(
  "FE|Buildings|non-Heating|Electricity|Conventional",
  "FE|Buildings|Heating|Electricity|Resistance",
  "FE|Buildings|Heating|Electricity|Heat pumps",
  "FE|Buildings|Heating|District Heating",
  "FE|Buildings|Heating|Solids",
  "FE|Buildings|Heating|Liquids",
  "FE|Buildings|Heating|Gases",
  "FE|Buildings|Heating|Hydrogen")
showAreaAndBarPlots(data, items, tot)
```

### Region Intercomparison FE|Buildings

```{r}
items <- c(
  "FE|Buildings|Heating",
  "FE|Buildings|Appliances and Light",
  "FE|Buildings|Cooking and Water",
  "FE|Buildings|Space Cooling",
  "FE|Buildings|Space Heating")
showMultiLinePlots(data, items[1:3])
showMultiLinePlots(data, items[4:5])
showMultiLinePlotsByGDP(data, items[1:3])
showMultiLinePlotsByGDP(data, items[4:5])
```


## Transport
### Energy Services for Passenger Transport
```{r}
items <- c(
  "ES|Transport|Pass pCap",
  "ES|Transport|Pass|Road|LDV pCap",
  "ES|Transport|Pass|non-LDV pCap")
showMultiLinePlots(data, items)    
showMultiLinePlotsByGDP(data, items)
```

```{r}
##---- ES passenger transport per capita (bar graph)----
items <- c(
  "ES|Transport|Pass|Road|LDV|BEV pCap",
  "ES|Transport|Pass|Road|LDV|FCEV pCap",
  "ES|Transport|Pass|Road|LDV|Gases pCap",
  "ES|Transport|Pass|Road|LDV|Hybrid Electric pCap",
  "ES|Transport|Pass|Road|LDV|Liquids pCap")
showAreaAndBarPlots(data, items)    
```

### Energy Services for Freight Transport per Capita
```{r}
items <- c(
  "ES|Transport|Freight pCap")
showMultiLinePlots(data, items)    
showMultiLinePlotsByGDP(data, items)
```


```{r}
items <- c(
  "ES|Transport|Freight|Road|Electric pCap",
  "ES|Transport|Freight|Road|FCEV pCap",
  "ES|Transport|Freight|Road|Gases pCap",
  "ES|Transport|Freight|Road|Liquids pCap")
showAreaAndBarPlots(data, items)
```

### LDV Vehicles Stock
```{r}
tot <- "Est LDV Stock"
items <- c(
  "Est EV LDV Stock",
  "Est H2 LDV Stock",
  "Est ICE LDV Stock")
showAreaAndBarPlots(data, items, tot)
```

### LDV Vehicles Sales
```{r}
tot <- "Est LDV Sales"
items <- c(      
  "Est EV LDV Sales",
  "Est H2 LDV Sales",
  "Est ICE LDV Sales")
showAreaAndBarPlots(data, items, tot)
```

### non-LDV Vehicles Stock
```{r}
tot <- "Services and Products|Transport|non-LDV|Stock|uedit"
items <- c(
  "Services and Products|Transport|non-LDV|Stock|apCarDiT",
  "Services and Products|Transport|non-LDV|Stock|apcarDiEffT",
  "Services and Products|Transport|non-LDV|Stock|apcarDiEffH2T")
showAreaAndBarPlots(data, items, tot)
```

### non-LDV Vehicles Sales
```{r}
tot <- "Services and Products|Transport|non-LDV|Sales|uedit"
items <- c(
  "Services and Products|Transport|non-LDV|Sales|apCarDiT",
  "Services and Products|Transport|non-LDV|Sales|apcarDiEffT",
  "Services and Products|Transport|non-LDV|Sales|apcarDiEffH2T")
showAreaAndBarPlots(data, items, tot) 
```

## Industry Production
### per sector
```{r}
showLinePlots(data, "Production|Industry|Steel")
showLinePlots(data, "Production|Industry|Steel|Primary") 
showLinePlots(data, "Production|Industry|Steel|Secondary")
showLinePlots(data, "Production|Industry|Cement")
showLinePlots(data, "Value Added|Industry|Chemicals")
showLinePlots(data, c("Value Added|Industry|Other Industry", "Value Added|Industry|other"))
```

### Region Intercomparison FE

```{r}
items <- c(
  "FE|Industry|Cement",
  "FE|Industry|Steel",
  "FE|Industry|Chemicals",
  "FE|Industry|Other Industry")
showMultiLinePlots(data, items[1:2])
showMultiLinePlots(data, items[3:4])
showMultiLinePlotsByGDP(data, items[1:2])
showMultiLinePlotsByGDP(data, items[3:4])
```

