# Summary

```{r eval=FALSE}
# NOTE: regex to remove units: "([^(]+) \([^)]+\)+" replace by "\1"
# NOTE: filtering and ordering scheme
data %>% 
    filter(variable %in% items) %>% 
    #mutate(variable = fct_relevel(variable, items)) %>% # order as in items
    #mutate(variable = fct_reorder2(variable, period, value, first2, .desc=FALSE)) %>% # order by value in first year
    #mutate(variable = fct_reorder(variable, value, sum)) %>% # order by area
    mutate(variable = fct_reorder(variable, value, sum)) ->
    d
```


```{r}
summary_default_plot <- function(tot, items) {
  data %>% 
    filter(variable %in% items) %>% 
    mutate(variable = fct_reorder(variable, value, sum)) ->
    d
  
  d %>% 
    filter(region == mainReg) %>% 
    mipArea(scales="free_y", total = F) + 
    theme(legend.position="none") + 
    geom_line(
      data = data %>% filter(region == mainReg, variable == tot), 
      mapping = aes(period, value),
      size=1.3) ->
    p1
  
  d %>% 
    filter(region == mainReg, period %in% y_bar) %>% 
    mipBarYearData() +
    theme(legend.position="none") ->
    p2
  
  d %>% 
    filter(region != mainReg, period %in% y_bar) %>% 
    mipBarYearData() +
    guides(fill=guide_legend(ncol=3)) ->
    p3
  
  d %>% 
    filter(region != mainReg) %>% 
    mipArea(scales="free_y", total = F) ->
    p4
  
  return(list(p1, p2, p3, p4))
}
```

```{r}
data %>% 
  filter(variable == "Population") %>% 
  select(model, scenario, region, period, value) %>% 
  mutate(population = value * 1e6) %>% # unit originally is million, now is 1
  select(!value) -> 
  dataPop
```



## GHG Emissions

```{r}
tot <- "Emi|GHG"
items <- c(
  "Emi|CO2|Energy",
  "Emi|CO2|Industrial Processes",
  "Emi|CO2|Land-Use Change",
  "Emi|GHG|CH4",
  "Emi|GHG|N2O",
  "Emi|GHG|F-Gases",
  "Emi|CO2|non-BECCS CDR")

p <- summary_default_plot(tot, items)

grid.arrange(
  p[[1]], p[[2]], p[[3]],
  layout_matrix = rbind(c(1, 3),
                        c(2, 3)))

p[[4]]
```

## GHG by sector (w/ gross emissions, excl. BECCS)

```{r}
tot <-"Emi|GHG"
items <- c("Emi|GHG|Gross|Energy|Supply|Electricity",
  "Emi|GHG|Gross|Energy|Supply|Non-electric",
  "Emi|GHG|Energy|Demand|Transport",
  "Emi|GHG|Energy|Demand|Buildings",
  "Emi|GHG|Gross|Energy|Demand|Industry",
  "Emi|GHG|Industrial Processes",
  "Emi|GHG|Agriculture",
  "Emi|GHG|Land-Use Change",
  "Emi|GHG|Waste",
  "Emi|GHG|F-Gas",
  "Emi|CO2|CDR|BECCS",
  "Emi|CO2|CDR|DACCS",
  "Emi|CO2|CDR|EW")

p <- summary_default_plot(tot, items)

grid.arrange(
  p[[1]], p[[2]], p[[3]],
  layout_matrix = rbind(c(1, 3),
                        c(2, 3)))

p[[4]]
```

## CO2 by sector (w/ gross emissions, excl. BECCS)

```{r CO2 by sector}
tot <- "Emi|CO2"
items <- c("Emi|CO2|Land-Use Change",
           "Emi|CO2|Industrial Processes",
           "Emi|CO2|Energy|Demand|Transport",
           "Emi|CO2|Gross|Energy|Demand|Industry",
           "Emi|CO2|Energy|Demand|Buildings",
           "Emi|CO2|Gross|Energy|Supply|Non-electric",
           "Emi|CO2|Gross|Energy|Supply|Electricity",
           "Emi|CO2|CDR|BECCS",
           "Emi|CO2|CDR|DACCS",
           "Emi|CO2|CDR|EW")
           
p <- summary_default_plot(tot, items)

grid.arrange(
  p[[1]], p[[2]], p[[3]],
  layout_matrix = rbind(c(1, 3),
                        c(2, 3)))

p[[4]]
```

```{r CO2 by sector cumulated}
tot <- "Emi|CO2|Cumulated"
items <- c(
  "Emi|CO2|Cumulated|Land-Use Change",
  "Emi|CO2|Cumulated|Industrial Processes",
  "Emi|CO2|Cumulated|Energy|Demand|Transport",
  "Emi|CO2|Cumulated|Energy|Demand|Industry",
  "Emi|CO2|Cumulated|Energy|Demand|Buildings",
  "Emi|CO2|Cumulated|Gross|Energy|Supply|Non-electric",
  "Emi|CO2|Cumulated|Gross|Energy|Supply|Electricity",
  "Emi|CO2|Cumulated|CDR|BECCS",
  "Emi|CO2|Cumulated|CDR|DACCS",
  "Emi|CO2|Cumulated|CDR|EW")

p <- summary_default_plot(tot, items)

grid.arrange(
  p[[1]], p[[2]], p[[3]],
  layout_matrix = rbind(c(1, 3),
                        c(2, 3)))

p[[4]]
```


## FE by sector

```{r FE by sector}
items <- c("FE|CDR",
           "FE|Transport",
           "FE|Buildings",
           "FE|Industry")

data %>% 
  filter(variable %in% items) %>% 
  mutate(variable = fct_reorder(variable, value, sum)) ->
  d

d %>% 
  filter(region == mainReg) %>% 
  mipArea(scales="free_y", total = T) + 
  theme(legend.position="none") ->
  p1

d %>% 
  filter(region == mainReg, period %in% y_bar) %>% 
  mipBarYearData() +
  theme(legend.position="none") ->
  p2

d %>% 
  filter(region != mainReg, period %in% y_bar) %>% 
  mipBarYearData() +
  guides(fill=guide_legend(ncol=3)) ->
  p3

d %>% 
  filter(region != mainReg) %>% 
  mipArea(scales="free_y", total = T) ->
  p4

grid.arrange(
  p1, p2, p3,
  layout_matrix = rbind(c(1, 3),
                        c(2, 3)))

p4
```

## FE per capita (by sector, time domain, area plot)

```{r FE per capita (by sector, time domain, area plot)}
items <- c(
  "FE|Transport",
	"FE|Buildings",
  "FE|Industry")

data %>% 
  filter(variable %in% items) %>% 
  left_join(dataPop) %>% 
  mutate(
    value = value / population * 1e9,
    variable = paste0(variable, "p. Cap."),
    unit = "GJ/yr" # from EJ to GJ
    ) %>%
  mutate(variable = fct_reorder(variable, value, sum)) ->
  d

d %>% 
  filter(region == mainReg) %>% 
  mipArea(scales="free_y", total = T) + 
  theme(legend.position="none") ->
  p1

d %>% 
  filter(region == mainReg, period %in% y_bar) %>% 
  mipBarYearData() +
  theme(legend.position="none") ->
  p2

d %>% 
  filter(region != mainReg, period %in% y_bar) %>% 
  mipBarYearData() +
  guides(fill=guide_legend(ncol=3)) ->
  p3

d %>% 
  filter(region != mainReg) %>% 
  mipArea(scales="free_y", total = T) ->
  p4

grid.arrange(
  p1, p2, p3,
  layout_matrix = rbind(c(1, 3),
                        c(2, 3)))

p4
```

## FE per capita (by sector, time domain, line graph)

```{r FE per capita (by sector, time domain, line graph), eval=FALSE}
items <- c(
  "FE",
  "FE|Transport",
  "FE|Buildings",
  "FE|Industry")

p <- lineplots_perCap(
  data=data,
  vars=items,
  percap_factor=1e3,
  ylabstr="FE per Cap. (GJ/yr)",
  global=T, histdata_plot=histData)

if("sr15data" %in% rownames(installed.packages()) & is.character(sr15marker_RCP)){

  variable <- Population <- `FE|Transport` <- `FE|Buildings` <- `FE|Industry` <- NULL
  region <- period <- `GDP|PPP` <- model <- value <- scenario <- FE <- NULL

  ## get marker scenario data
  marker_items <- c(
    "Final Energy",
    paste0("Final Energy|", c("Industry", "Residential and Commercial", "Transportation")),
    "Population")
  sr15dt <- as.data.table(sr15data::sr15data)[
    region == "World"][
  , region := mainReg][
    data.table(period=y), on="period"]
  sr15scens <- data.table(scenario=paste0("SSP", 1:5, "-", sr15marker_RCP),
                          model=c("IMAGE 3.0.1",
                                  "MESSAGE-GLOBIOM 1.0",
                                  "AIM/CGE 2.0",
                                  "GCAM 4.2",
                                  "REMIND-MAgPIE 1.5"))
  markers <- sr15dt[sr15scens, on=c("model", "scenario")][
    variable %in% marker_items][
  , variable := gsub("Final Energy", "FE", variable)][
  , variable := gsub("Transportation", "Transport", variable)][
  , variable := gsub("Residential and Commercial", "Buildings", variable)][
  , scenario := gsub("Baseline", "Base", scenario)][, "unit" := NULL]

  markers_wide <- data.table::dcast(markers, ... ~ variable)

  markers_wide[, `:=`("FE|Transport" = `FE|Transport`/Population*1e3,
                      "FE|Buildings" = `FE|Buildings`/Population*1e3,
                      "FE|Industry" = `FE|Industry`/Population*1e3,
                      "FE" = `FE`/Population*1e3), by=c("model")]

  markers <- data.table::melt(markers_wide, id.vars=c("model", "scenario", "region", "period"))[
                           variable != "Population"]

  p <- p + geom_line(data=markers, aes(x=period, y=value, group=scenario, color=scenario),
                     size=2, alpha=1/4)

}

swfigure(sw,print,p,sw_option="height=9,width=16")

## Second page, with color coded regions

p <- lineplots_perCap(data, items, 1e3, "FE per Cap. (GJ/yr)", global = F, histdata_plot = histData)
swfigure(sw,print,p,sw_option="height=9,width=16")

swlatex(sw,"\\twocolumn")


## ---- FE per capita by sector (GDP domain)----
```


```{r eval=FALSE}
swlatex(sw,"\\onecolumn")
swlatex(sw,"\\subsection{FE per capita (by sector, GDP)}")

items<- c(#"FE|CDR" ,
		"FE|Transport",
		#"FE|Transport|w/o Bunkers"
          "FE|Buildings",
          "FE|Industry")

p <- lineplots_perCap(data, items, 1e3, "FE per Cap. (GJ/yr)", global = T,
                      per_gdp = T, histdata_plot = histData)
swfigure(sw,print,p,sw_option="height=9,width=16")

p <- lineplots_perCap(data, items, 1e3, "FE per Cap. (GJ/yr)", per_gdp = T,
                      histdata_plot = histData)
swfigure(sw,print,p,sw_option="height=9,width=16")

swlatex(sw,"\\twocolumn")
```


```{r eval=FALSE}
## ---- FE by carrier ----

swlatex(sw,"\\subsection{FE by carrier}")

items<- c("FE|Solids",
          "FE|Liquids",
          "FE|Gases",
          "FE|Heat",
          "FE|Hydrogen",
          "FE|Electricity")
var <- data[,,intersect(items,getNames(data,dim=3))]

p <- mipArea(var[mainReg,,],scales="free_y")
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=3.5,width=7")

p <- mipBarYearData(var[mainReg,y_bar,])
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=4.5,width=7")

p <- mipBarYearData(var[,y_bar,][mainReg,,,invert=TRUE])
swfigure(sw,print,p,sw_option="height=9,width=8")

swlatex(sw,"\\onecolumn")
p <- mipArea(var[mainReg,,,invert=TRUE],scales="free_y")
swfigure(sw,print,p,sw_option="height=8,width=16")
swlatex(sw,"\\twocolumn")
```


```{r eval=FALSE}
## ---- FE Industry by carrier ----

swlatex(sw,"\\subsection{FE Industry by carrier}")

items<- c("FE|Industry|Solids",
          "FE|Industry|Liquids",
          "FE|Industry|Gases",
          "FE|Industry|Heat",
          "FE|Industry|Hydrogen",
          "FE|Industry|Electricity")
var <- data[,,intersect(items,getNames(data,dim=3))]

p <- mipArea(var[mainReg,,],scales="free_y")
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=3.5,width=7")

p <- mipBarYearData(var[mainReg,y_bar,])
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=4.5,width=7")

p <- mipBarYearData(var[,y_bar,][mainReg,,,invert=TRUE])
swfigure(sw,print,p,sw_option="height=9,width=8")

swlatex(sw,"\\onecolumn")
p <- mipArea(var[mainReg,,,invert=TRUE],scales="free_y")
swfigure(sw,print,p,sw_option="height=8,width=16")
swlatex(sw,"\\twocolumn")
```


```{r eval=FALSE}
## ---- FE Buildings by carrier ----

swlatex(sw,"\\subsection{FE Buildings by carrier}")

items<- c("FE|Buildings|Solids",
          "FE|Buildings|Liquids",
          "FE|Buildings|Gases",
          "FE|Buildings|Heat",
          "FE|Buildings|Hydrogen",
          "FE|Buildings|Electricity")
var <- data[,,intersect(items,getNames(data,dim=3))]

p <- mipArea(var[mainReg,,],scales="free_y")
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=3.5,width=7")

p <- mipBarYearData(var[mainReg,y_bar,])
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=4.5,width=7")

p <- mipBarYearData(var[,y_bar,][mainReg,,,invert=TRUE])
swfigure(sw,print,p,sw_option="height=9,width=8")

swlatex(sw,"\\onecolumn")
p <- mipArea(var[mainReg,,,invert=TRUE],scales="free_y")
swfigure(sw,print,p,sw_option="height=8,width=16")
swlatex(sw,"\\twocolumn")
```


```{r eval=FALSE}
## ---- FE Transport by carrier ----

swlatex(sw,"\\subsection{FE Transport by carrier}")
items<- c (
  "FE|Transport|Electricity",
  "FE|Transport|Hydrogen",
  "FE|Transport|Liquids",
#"FE|Transport|Liquids|w/o Bunkers",
#"FE|Transport|Liquids|Bunkers",
  "FE|Transport|Gases"
)

var <- data[,,intersect(items,getNames(data,dim=3))]

p <- mipArea(var[mainReg,,],scales="free_y")
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=3.5,width=7")

p <- mipBarYearData(var[mainReg,y_bar,])
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=4.5,width=7")

p <- mipBarYearData(var[,y_bar,][mainReg,,,invert=TRUE])
swfigure(sw,print,p,sw_option="height=9,width=8")

swlatex(sw,"\\onecolumn")
p <- mipArea(var[mainReg,,,invert=TRUE],scales="free_y")
swfigure(sw,print,p,sw_option="height=8,width=16")
swlatex(sw,"\\twocolumn")
```


```{r eval=FALSE}
## ---- FE CDR by carrier ----

swlatex(sw,"\\subsection{FE CDR by carrier}")

items<- c("FE|CDR|Liquids",
          "FE|CDR|Gases",
          "FE|CDR|Hydrogen",
          "FE|CDR|Electricity")
var <- data[,,intersect(items,getNames(data,dim=3))]

p <- mipArea(var[mainReg,,],scales="free_y")
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=3.5,width=7")

p <- mipBarYearData(var[mainReg,y_bar,])
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=4.5,width=7")

p <- mipBarYearData(var[,y_bar,][mainReg,,,invert=TRUE])
swfigure(sw,print,p,sw_option="height=9,width=8")

swlatex(sw,"\\onecolumn")
p <- mipArea(var[mainReg,,,invert=TRUE],scales="free_y")
swfigure(sw,print,p,sw_option="height=8,width=16")
swlatex(sw,"\\twocolumn")
```


```{r eval=FALSE}
## ---- SE Electricity by carrier ----

swlatex(sw,"\\subsection{SE Electricity by carrier}")

items<- c ("SE|Electricity|Coal|w/ CCS",
           "SE|Electricity|Coal|w/o CCS",
           "SE|Electricity|Oil",
           "SE|Electricity|Gas|w/ CCS",
           "SE|Electricity|Gas|w/o CCS",
           "SE|Electricity|Geothermal",
           "SE|Electricity|Hydro",
           "SE|Electricity|Nuclear",
           "SE|Electricity|Biomass|w/ CCS",
           "SE|Electricity|Biomass|w/o CCS",
           "SE|Electricity|Solar|CSP",
           "SE|Electricity|Solar|PV",
           "SE|Electricity|Hydrogen",
           "SE|Electricity|Net Imports")

if ("SE|Electricity|Wind|Offshore" %in% magclass::getNames(data, dim = 3)) {
  items <- append(items, c( "SE|Electricity|Wind|Onshore",
                            "SE|Electricity|Wind|Offshore"))
 } else {
   items <- append(items, c( "SE|Electricity|Wind"))
   # var[,, "SE|Electricity|Wind|Onshore"] <- var[,,"SE|Electricity|Wind"]
 }

var <- data[,,intersect(items,getNames(data,dim=3))]

# correct SE|Electricity|Hydrogen, current value is FE, SE can be calculated by estimating turbine efficiency
var[,,"SE|Electricity|Hydrogen"] <- var[,,"SE|Electricity|Hydrogen"] / 0.4

p <- mipArea(var[mainReg,,],scales="free_y")
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=3.5,width=7")

p <- mipBarYearData(var[mainReg,y_bar,])
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=4.5,width=7")

p <- mipBarYearData(var[,y_bar,][mainReg,,,invert=TRUE])
swfigure(sw,print,p,sw_option="height=9,width=8")

swlatex(sw,"\\onecolumn")
p <- mipArea(var[mainReg,,,invert=TRUE],scales="free_y")
swfigure(sw,print,p,sw_option="height=8,width=16")
swlatex(sw,"\\twocolumn")

if ("SE|Electricity|Wind|Offshore" %in% magclass::getNames(data, dim = 3)) {
  
  swlatex(sw,"\\subsubsection{SE Wind Onshore}")
  var0 <- "SE|Electricity|Wind|Onshore"
  
  p <-mipLineHistorical(var[mainReg,,var0],
                        ylab=var0,scales="free_y",plot.priority=c("x_hist","x","x_proj"))
  swfigure(sw,print,p,sw_option="height=8,width=8")
  p <- mipLineHistorical(var[,,var0][mainReg,,,invert=TRUE],
                         ylab=var0,scales="free_y",plot.priority=c("x_hist","x","x_proj"),facet.ncol=3)
  swfigure(sw,print,p,sw_option="height=9,width=8")
  
  swlatex(sw,"\\subsubsection{SE Wind Offshore}")
  var0 <- "SE|Electricity|Wind|Offshore"
  p <-mipLineHistorical(var[mainReg,,var0],
                        ylab=var0,scales="free_y",plot.priority=c("x_hist","x","x_proj"))
  swfigure(sw,print,p,sw_option="height=8,width=8")
  p <- mipLineHistorical(var[,,var0][mainReg,,,invert=TRUE],
                         ylab=var0,scales="free_y",plot.priority=c("x_hist","x","x_proj"),facet.ncol=3)
  swfigure(sw,print,p,sw_option="height=9,width=8")
}
```


```{r eval=FALSE}
## ---- SE non-electric by carrier ----

swlatex(sw,"\\subsection{SE non-electric by carrier}")
## XXX
```


```{r eval=FALSE}
## ---- PE by sector ----

swlatex(sw,"\\subsection{PE by sector}")
## XXX
```


```{r eval=FALSE}
## ---- PE by carrier ----

swlatex(sw,"\\subsection{PE by carrier}")

items <-c("PE|Coal",
          "PE|Oil",
          "PE|Gas",
          "PE|Biomass",
          "PE|Nuclear",
          "PE|Solar",
          "PE|Wind",
          "PE|Hydro",
          "PE|Geothermal")
var <- data[,,intersect(items,getNames(data,dim=3))]

p <- mipArea(var[mainReg,,],scales="free_y")
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=3.5,width=7")

p <- mipBarYearData(var[mainReg,y_bar,])
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=4.5,width=7")

p <- mipBarYearData(var[,y_bar,][mainReg,,,invert=TRUE])
swfigure(sw,print,p,sw_option="height=9,width=8")

swlatex(sw,"\\onecolumn")
p <- mipArea(var[mainReg,,,invert=TRUE],scales="free_y")
swfigure(sw,print,p,sw_option="height=8,width=16")
swlatex(sw,"\\twocolumn")
```


```{r eval=FALSE}
## ---- CO2 Prices ----

swlatex(sw,"\\subsection{CO2 Prices}")

p <- mipLineHistorical(data[mainReg,,"Price|Carbon"],x_hist=NULL,
                       ylab='Price|Carbon [US$2005/t CO2]',scales="free_y",plot.priority=c("x_hist","x","x_proj"))
p <- p + theme(legend.position="none")
swfigure(sw,print,p,sw_option="height=8,width=8")
#p <- mipLineHistorical(data[mainReg,,"Price|Carbon"],x_hist=NULL,
#                       ylab='Price|Carbon_log [US$2005/t CO2]',ybreaks=c(20,30,40,50,60,75,100,200,500,1000,2000,3000),
#                       ylim=c(0,3000),ylog=TRUE)
#swfigure(sw,print,p,sw_option="height=4.5,width=7")
p <- mipLineHistorical(data[,,"Price|Carbon"][mainReg,,,invert=TRUE],x_hist=NULL,
                       ylab='Price|Carbon [US$2005/t CO2]',scales="free_y",plot.priority=c("x_hist","x","x_proj"),facet.ncol=3)
swfigure(sw,print,p,sw_option="height=9,width=8")

swlatex(sw,"\\onecolumn")

p <- mipLineHistorical(
  data[,,"Price|Carbon"][
    mainReg,,,invert=TRUE],
  ylab='Price|Carbon [US$2005/t CO2]',
  scales="free_y",
  plot.priority=c("x_hist","x","x_proj"),
  color.dim="region",
  facet.dim="scenario",
  facet.ncol=2) +
  theme(legend.position="right")
swfigure(sw,print,p,sw_option="height=9,width=16")

d <- data[mainReg,,"Price|Carbon|ETS"]
if (isTRUE(any(d!=0))) {
  swlatex(sw,"\\twocolumn")
  p <- mipLineHistorical(d,x_hist=NULL,
                         ylab='Price|Carbon|ETS [US$2005/t CO2]',scales="free_y",plot.priority=c("x_hist","x","x_proj"))
  p <- p + theme(legend.position="none")
  swfigure(sw,print,p,sw_option="height=8,width=8")
}
d <- data[,,"Price|Carbon|ETS"][mainReg,,,invert=TRUE]
if (isTRUE(any(d!=0))) {
  p <- mipLineHistorical(d,x_hist=NULL,
                         ylab='Price|Carbon|ETS [US$2005/t CO2]',scales="free_y",plot.priority=c("x_hist","x","x_proj"),facet.ncol=3)
  swfigure(sw,print,p,sw_option="height=9,width=8")
}

d <- data[mainReg,,"Price|Carbon|ESR"]
if (isTRUE(any(d!=0))) {
  swlatex(sw,"\\twocolumn")
  p <- mipLineHistorical(,x_hist=NULL,
                         ylab='Price|Carbon|ESR [US$2005/t CO2]',scales="free_y",plot.priority=c("x_hist","x","x_proj"))
  p <- p + theme(legend.position="none")
  swfigure(sw,print,p,sw_option="height=8,width=8")
}
d <- data[,,"Price|Carbon|ESR"][mainReg,,,invert=TRUE]
if (isTRUE(any(d!=0))) {
  p <- mipLineHistorical(d,x_hist=NULL,
                         ylab='Price|Carbon|ESR [US$2005/t CO2]',scales="free_y",plot.priority=c("x_hist","x","x_proj"),facet.ncol=3)
  swfigure(sw,print,p,sw_option="height=9,width=8")
}
swlatex(sw,"\\twocolumn")


if("Policy Cost|Consumption Loss" %in% magclass::getNames(data,dim=3)) {
  ## ---- Policy Cost|Consumption Loss ----
  swlatex(sw,"\\subsection{Policy Costs}")

  p <- mipLineHistorical(
    data[mainReg,,"Policy Cost|Consumption Loss"],
    x_hist=NULL,
    ylab='Policy Cost|Consumption Loss [billion US$2005/yr]',
    scales="free_y",
    plot.priority=c("x_hist","x","x_proj"))
  swfigure(sw,print,p,sw_option="height=8,width=8")

  p <- mipLineHistorical(
    data[,,"Policy Cost|Consumption Loss"][
      mainReg,,,invert=TRUE],
    x_hist=NULL,
    ylab='Policy Cost|Consumption Loss [billion US$2005/yr]',
    scales="free_y",
    plot.priority=c("x_hist","x","x_proj"),
    facet.ncol=3)
  swfigure(sw,print,p,sw_option="height=9,width=8")

  p <- mipLineHistorical(
    data[mainReg,,"Policy Cost|Consumption Loss|Relative to Reference Consumption"],
    x_hist=NULL,
    ylab='Policy Cost|Consumption Loss|Relative to Reference Consumption [%]',
    scales="free_y",
    plot.priority=c("x_hist","x","x_proj"))
  swfigure(sw,print,p,sw_option="height=9,width=8")

  p <- mipLineHistorical(
    data[,,"Policy Cost|Consumption Loss|Relative to Reference Consumption"][
      mainReg,,,invert=TRUE],
    x_hist=NULL,
    ylab='Policy Cost|Consumption Loss|Relative to Reference Consumption [%]',
    scales="free_y",
    plot.priority=c("x_hist","x","x_proj"),
    facet.ncol=3)
  swfigure(sw,print,p,sw_option="height=9,width=8")
}

if("Policy Cost|GDP Loss" %in% magclass::getNames(data,dim=3)) {
  ## ---- Policy Cost|GDP Loss ----
  swlatex(sw,"\\subsection{Policy Costs}")
  
  p <- mipLineHistorical(
    data[mainReg,,"Policy Cost|GDP Loss"],
    x_hist=NULL,
    ylab='Policy Cost|GDP Loss [billion US$2005/yr]',
    scales="free_y",
    plot.priority=c("x_hist","x","x_proj"))
  swfigure(sw,print,p,sw_option="height=8,width=8")
  
  p <- mipLineHistorical(
    data[,,"Policy Cost|GDP Loss"][
      mainReg,,,invert=TRUE],
    x_hist=NULL,
    ylab='Policy Cost|GDP Loss [billion US$2005/yr]',
    scales="free_y",
    plot.priority=c("x_hist","x","x_proj"),
    facet.ncol=3)
  swfigure(sw,print,p,sw_option="height=9,width=8")
}
```

