# CES Function

## CES Prices (CES Derivatives) 

### Buildings

```{r CES Prices Buildings}

showLinePlots(data, "Internal|CES Function|CES Price|fegab")
showLinePlots(data, "Internal|CES Function|CES Price|feh2b")
showLinePlots(data, "Internal|CES Function|CES Price|fesob")
showLinePlots(data, "Internal|CES Function|CES Price|fehob")
showLinePlots(data, "Internal|CES Function|CES Price|feelhpb")
showLinePlots(data, "Internal|CES Function|CES Price|feelrhb")
showLinePlots(data, "Internal|CES Function|CES Price|feheb")

showLinePlots(data, "Internal|CES Function|CES Price|enhb")
showLinePlots(data, "Internal|CES Function|CES Price|enb")

```


### Industry

#### Total Industry

```{r CES Prices Total Industry}
showLinePlots(data, "Internal|CES Function|CES Price|ue_industry")
```


#### Steel

```{r CES Prices Steel}

showLinePlots(data, "Internal|CES Function|CES Price|feso_steel")
showLinePlots(data, "Internal|CES Function|CES Price|feli_steel")
showLinePlots(data, "Internal|CES Function|CES Price|fega_steel")
showLinePlots(data, "Internal|CES Function|CES Price|feh2_steel")
showLinePlots(data, "Internal|CES Function|CES Price|feel_steel_primary")
showLinePlots(data, "Internal|CES Function|CES Price|feel_steel_secondary")


showLinePlots(data, "Internal|CES Function|CES Price|en_steel_primary")

showLinePlots(data, "Internal|CES Function|CES Price|ue_steel_primary")
showLinePlots(data, "Internal|CES Function|CES Price|ue_steel_secondary")
```

#### Cement

```{r CES Prices Cement}

showLinePlots(data, "Internal|CES Function|CES Price|feso_cement")
showLinePlots(data, "Internal|CES Function|CES Price|feli_cement")
showLinePlots(data, "Internal|CES Function|CES Price|fega_cement")
showLinePlots(data, "Internal|CES Function|CES Price|feh2_cement")
showLinePlots(data, "Internal|CES Function|CES Price|feel_cement")

showLinePlots(data, "Internal|CES Function|CES Price|en_cement")

showLinePlots(data, "Internal|CES Function|CES Price|ue_cement")
```

#### Chemicals

```{r CES Prices Chemicals}

showLinePlots(data, "Internal|CES Function|CES Price|feso_chemicals")
showLinePlots(data, "Internal|CES Function|CES Price|feli_chemicals")
showLinePlots(data, "Internal|CES Function|CES Price|fega_chemicals")
showLinePlots(data, "Internal|CES Function|CES Price|feh2_chemicals")
showLinePlots(data, "Internal|CES Function|CES Price|feelhth_chemicals")

showLinePlots(data, "Internal|CES Function|CES Price|en_chemicals")

showLinePlots(data, "Internal|CES Function|CES Price|ue_chemicals")
```


#### Other Industry

```{r CES Prices Other Industry}

showLinePlots(data, "Internal|CES Function|CES Price|feso_otherInd")
showLinePlots(data, "Internal|CES Function|CES Price|feli_otherInd")
showLinePlots(data, "Internal|CES Function|CES Price|fega_otherInd")
showLinePlots(data, "Internal|CES Function|CES Price|feh2_otherInd")
showLinePlots(data, "Internal|CES Function|CES Price|feelhth_otherInd")

showLinePlots(data, "Internal|CES Function|CES Price|en_otherInd")

showLinePlots(data, "Internal|CES Function|CES Price|ue_otherInd")
```


## Marginal Rates of Substitution (selected)


### Buildings

```{r MRS Buildings}
showLinePlots(data, "Internal|CES Function|MRS|feelhpb|fegab")
showLinePlots(data, "Internal|CES Function|MRS|feelhpb|fehob")
showLinePlots(data, "Internal|CES Function|MRS|feelhpb|fesob")
showLinePlots(data, "Internal|CES Function|MRS|feelhpb|feelrhb")

showLinePlots(data, "Internal|CES Function|MRS|feelh2b|fegab")
```


### Industry

#### Steel

```{r MRS Steel}
showLinePlots(data, "Internal|CES Function|MRS|feel_steel_secondary|feso_steel")
showLinePlots(data, "Internal|CES Function|MRS|feh2_steel|feso_steel")
```



#### Cement

```{r MRS Cement}
showLinePlots(data, "Internal|CES Function|MRS|feh2_cement|fega_cement")
showLinePlots(data, "Internal|CES Function|MRS|feh2_cement|feso_cement")
```


#### Chemicals

```{r MRS Chemicals}
showLinePlots(data, "Internal|CES Function|MRS|feelhth_chemicals|fega_chemicals")
showLinePlots(data, "Internal|CES Function|MRS|feelhth_chemicals|feli_chemicals")
showLinePlots(data, "Internal|CES Function|MRS|feh2_chemicals|fega_chemicals")
showLinePlots(data, "Internal|CES Function|MRS|feh2_chemicals|feli_chemicals")
```


#### Other Industry

```{r MRS Other Industry}
showLinePlots(data, "Internal|CES Function|MRS|feelhth_otherInd|fega_otherInd")
showLinePlots(data, "Internal|CES Function|MRS|feelhth_otherInd|feli_otherInd")
showLinePlots(data, "Internal|CES Function|MRS|feelhth_otherInd|feso_otherInd")

showLinePlots(data, "Internal|CES Function|MRS|feh2_otherInd|fega_otherInd")
showLinePlots(data, "Internal|CES Function|MRS|feh2_otherInd|feli_otherInd")
showLinePlots(data, "Internal|CES Function|MRS|feh2_otherInd|feso_otherInd")
```




## CES Function Value (selected)

### Buildings


```{r Buildings Value}

showLinePlots(data, "Internal|CES Function|Value|enb")
showLinePlots(data, "Internal|CES Function|Value|enhb")
showLinePlots(data, "Internal|CES Function|Value|feelcb")
```

### Industry

```{r Industry Value}

showLinePlots(data, "Internal|CES Function|Value|ue_industry")
showLinePlots(data, "Internal|CES Function|Value|ue_steel")
showLinePlots(data, "Internal|CES Function|Value|ue_cement")
showLinePlots(data, "Internal|CES Function|Value|ue_chemicals")
showLinePlots(data, "Internal|CES Function|Value|ue_otherInd")
```

### Transport

```{r Transport Value}

showLinePlots(data, "Internal|CES Function|Value|entrp")

```
