# Energy Demand
## Final Energy line plot
```{r}
showLinePlots(data, "FE")
showLinePlots(data, "FE|Electricity")
showLinePlots(data, "FE|Gases")
showLinePlots(data, "FE|Heat")
showLinePlots(data, "FE|Solids")
showLinePlots(data, "FE|Liquids")
showLinePlots(data, "FE|Hydrogen")
```

## Buildings Final Energy
```{r}
showLinePlots(data, "FE|Buildings")
showLinePlots(data, "FE|Buildings|Electricity")
showLinePlots(data, "FE|Buildings|Gases")
showLinePlots(data, "FE|Buildings|Heat")
showLinePlots(data, "FE|Buildings|Solids")
showLinePlots(data, "FE|Buildings|Liquids")
showLinePlots(data, "FE|Buildings|Hydrogen")
```

## Industry Final Energy
```{r}
showLinePlots(data, "FE|Industry")
showLinePlots(data, "FE|Industry|Electricity")
showLinePlots(data, "FE|Industry|Gases")
showLinePlots(data, "FE|Industry|Heat")
showLinePlots(data, "FE|Industry|Solids")
showLinePlots(data, "FE|Industry|Liquids")
showLinePlots(data, "FE|Industry|Hydrogen")
``` 

```{r}
showLinePlots(data, "FE|Industry|Liquids|Biomass")
showLinePlots(data, "FE|Industry|Solids|Biomass")
showLinePlots(data, "FE|Industry|Gases|Biomass")
showLinePlots(data, "FE|Industry|Liquids|Fossil")
showLinePlots(data, "FE|Industry|Solids|Fossil")
showLinePlots(data, "FE|Industry|Gases|Fossil")
```


### FE mix Steel
```{r}
tot <- "FE|Industry|Steel"
items <- c(
  "FE|Industry|Steel|Heat",
  "FE|Industry|Steel|Hydrogen",
  "FE|Industry|Steel|Solids",
  "FE|Industry|Steel|Liquids",
  "FE|Industry|Steel|Gases",
  "FE|Industry|Steel|Primary|Electricity",
  "FE|Industry|Steel|Secondary|Electricity")
showAreaAndBarPlots(data, items, tot)
```

### FE mix Cement
```{r}
tot <- "FE|Industry|Cement"
items <- c(
  "FE|Industry|Cement|Heat",
  "FE|Industry|Cement|Hydrogen",
  "FE|Industry|Cement|Solids",
  "FE|Industry|Cement|Liquids",
  "FE|Industry|Cement|Gases",
  "FE|Industry|Cement|Electricity")
showAreaAndBarPlots(data, items, tot)
```

### FE mix Chemicals
```{r}
tot <- "FE|Industry|Chemicals"
items <- c (
  "FE|Industry|Chemicals|Heat",
  "FE|Industry|Chemicals|Hydrogen",
  "FE|Industry|Chemicals|Solids",
  "FE|Industry|Chemicals|Liquids",
  "FE|Industry|Chemicals|Gases",
  "FE|Industry|Chemicals|Electricity|Mechanical work and low-temperature heat",
  "FE|Industry|Chemicals|Electricity|High-temperature heat")
showAreaAndBarPlots(data, items, tot)
```

### FE mix Other Industry
```{r}
tot <- "FE|Industry|Other Industry"
items <- c(
  "FE|Industry|Other Industry|Heat",
  "FE|Industry|Other Industry|Hydrogen",
  "FE|Industry|Other Industry|Solids",
  "FE|Industry|Other Industry|Liquids",
  "FE|Industry|Other Industry|Gases",
  "FE|Industry|Other Industry|Electricity|Mechanical work and low-temperature heat",
  "FE|Industry|Other Industry|Electricity|High-temperature heat")
showAreaAndBarPlots(data, items, tot)
```

### FE|Industry|* line plots
```{r}
showLinePlots(data, "FE|Industry|Steel")
showLinePlots(data, "FE|Industry|Steel|Primary" )
showLinePlots(data, "FE|Industry|Steel|Secondary")
showLinePlots(data, "FE|Industry|Cement")
showLinePlots(data, "FE|Industry|Chemicals")
showLinePlots(data, c("FE|Industry|Other Industry", "FE|Industry|other"))
```

## Transport Final Energy 
```{r}
showLinePlots(data, c("FE|Transport", "FE|Transport w/ Bunkers"))
showLinePlots(data, c("FE|Transport|w/o Bunkers", "FE|Transport")) # TODO: Eurostat.
```

### Transport per type
```{r}
tot <- "FE|Transport"
items <- c(
  "FE|Transport|LDV|Liquids",
  "FE|Transport|LDV|Gases",
  "FE|Transport|LDV|Electricity",
  "FE|Transport|LDV|Hydrogen",
  "FE|Transport|non-LDV|w/o Bunkers|Liquids",
  "FE|Transport|non-LDV|w/o Bunkers|Gases",
  "FE|Transport|non-LDV|w/o Bunkers|Electricity",
  "FE|Transport|non-LDV|w/o Bunkers|Hydrogen",
  "FE|Transport|non-LDV|Bunkers|Liquids",
  "FE|Transport|non-LDV|Bunkers|Gases",
  "FE|Transport|non-LDV|Bunkers|Electricity",
  "FE|Transport|non-LDV|Bunkers|Hydrogen")
if (all(items %in% variables)) showAreaAndBarPlots(data, items, tot)
```

### per carrier with Bunkers

```{r}
# TODO: for historical: Eurostat.FE|Transport|Bunkers is calculated as FE|Transport w/ Bunkers - FE|Transport. But Eurostat.FE|Transport may not exist
showLinePlots(data, "FE|Transport|Bunkers")
```
```{r}
showLinePlots(data, c("FE|Transport|Liquids", "FE|Transport|Liquids w/ Bunkers"))
showLinePlots(data, "FE|Transport|Gases")
showLinePlots(data, "FE|Transport|Electricity")
showLinePlots(data, "FE|Transport|Hydrogen")
```

### per carrier Without Bunkers
```{r}
# TODO: bunkers naming problem, conflict with hist vs scenario
showLinePlots(data, c("FE|Transport|w/o Bunkers|Liquids", "FE|Transport|Liquids"))
```

```{r}
showLinePlots(data, c("FE|Transport|w/o Bunkers|Gases", "FE|Transport|Gases"))
showLinePlots(data, c("FE|Transport|w/o Bunkers|Electricity", "FE|Transport|Electricity"))
showLinePlots(data, "FE|Transport|w/o Bunkers|Hydrogen")
```

