# uncomment to skip test
# skip("Skip GDX test")

# Check REMIND output. dt is a data.table in *wide* format,
# i.e., variables are columns. `eqs` is a list of equations of the form
# list(LHS = "RHS", ...). The scope determines if the equations
# should be checked for regions ("regional"), only globally ("world") or
# both ("all"). Sensitivity determines the allowed offset when comparing
# LHS to RHS
library(dplyr)
library(gdx)

test_that("Test if REMIND reporting is produced as it should and check data integrity", {
  skip_if_not(as.logical(gdxrrw::igdx(silent = TRUE)), "gdxrrw is not initialized properly")

  # add GDXs for comparison here:
  gdxPaths <- NULL

  gdxList <- c("fulldata-release.gdx" = "https://rse.pik-potsdam.de/data/example/remind2_test-convGDX2MIF_fulldata.gdx",
               "fulldata-AMT.gdx"     = "https://rse.pik-potsdam.de/data/example/remind2_test-convGDX2MIF_SSP2EU-PkBudg650-AMT.gdx")

  if (length(gdxPaths) == 0) {
    for (i in seq_along(gdxList)) {
      from <- gdxList[i]
      to   <- file.path(tempdir(), names(gdxList[i]))
      if (!file.exists(to)) {
        utils::download.file(from, to, mode = "wb", quiet = TRUE)
      }
      gdxPaths <- c(gdxPaths, to)
    }
  }

  checkPiamTemplates <- function(computedVariables) {
    # if you add a new template here, make sure to adjust the piamInterfaces version in the DESCRIPTION
    templates <- c("AR6", "AR6_NGFS", "ELEVATE", "NAVIGATE", "SHAPE")
    for (template in templates) {
      templateVariables <- template %>%
        piamInterfaces::getREMINDTemplateVariables() %>%
        unique() %>%
        deletePlus()
      expect_true(any(computedVariables %in% templateVariables))
      missingVariables <- setdiff(templateVariables, computedVariables)
      if (length(missingVariables) > 0) {
        warning("The following variables are expected in the piamInterfaces package ",
                "for template ", template,
                ", but cannot be found in the reporting generated by ", gdxPath, ":\n ",
                paste(missingVariables, collapse = ",\n "))
      }
    }
  }

  # uncomment to add current calibration gdxes
  # gdxPaths <- c(gdxPaths, Sys.glob("/p/projects/remind/inputdata/CESparametersAndGDX/*.gdx"))
  # uncomment to add debugging example gdx files
  # gdxPaths <- c(gdxPaths, Sys.glob("/p/projects/remind/debugging/gdx-examples/*.gdx"))

  numberOfMifs <- 0

  for (gdxPath in gdxPaths) {
    numberOfMifs <- numberOfMifs + 1

    message("Running convGDX2MIF(", gdxPath, ")...")
    refpolicycost <- if (gdxPath == gdxPaths[[1]]) gdxPath else NULL
    mifContent <- convGDX2MIF(gdxPath, gdx_refpolicycost = refpolicycost, testthat = TRUE)

    expect_no_warning(piamInterfaces::checkVarNames(getNames(mifContent, dim = 3)))

    computedVariables <- deletePlus(getItems(mifContent, dim = 3.3))
    computedVariables <- gsub("\\(\\)", "(unitless)", computedVariables)
    checkPiamTemplates(computedVariables)
    magclass::write.report(
      x = magclass::collapseNames(mifContent),
      file = file.path(tempdir(), paste0(numberOfMifs, ".mif")),
      scenario = paste0(magclass::getItems(mifContent, dim = "scenario"), numberOfMifs),
      model = "REMIND"
    )
  }
  # create a second file, so we can actually check the comparison code
  if (numberOfMifs == 1) {
    numberOfMifs <- numberOfMifs + 1
    magclass::write.report(
      x = magclass::collapseNames(mifContent),
      file = file.path(tempdir(), paste0(numberOfMifs, ".mif")),
      scenario = paste0(magclass::getItems(mifContent, dim = "scenario"), numberOfMifs),
      model = "REMIND"
    )
  }

  message("Checking compareScenarios...")
  myMifs <- file.path(tempdir(), paste0(seq_len(numberOfMifs), ".mif"))
  histMif <- file.path(tempdir(), "historical.mif")
  if (!file.exists(histMif)) {
    utils::download.file("https://rse.pik-potsdam.de/data/example/historical.mif", histMif, quiet = TRUE)
  }

  suppressWarnings(
    capture.output( # Do not show stdout text.
      compareScenarios2(
        mifScen = myMifs,
        mifHist = histMif,
        outputFormat = "pdf",
        outputFile = "cs2_test",
        outputDir = tempdir(),
        sections = 0
      )
    ) # Render only the info section.
  )
  expect_true(file.exists(file.path(tempdir(), "cs2_test.pdf")))
  unlink(tempdir(), recursive = TRUE)
  tempdir(TRUE)
})
