#' Read in GDX and extract climate assessment variables
#'
#' Read climate assessment variables from GDX file
#'
#' @param gdx A GDX as created by readGDX, or the file name of a gdx
#' @param output Existing magclass object containing data generated by other report*.R functions
#'
#' @author Tonn Rüter
#' @examples
#' \dontrun{
#' output <- reportMacroEconomy(gdx, NULL)
#' reportClimate(gdx, output)
#' }
#'
#' @export
#' @importFrom gdx readGDX
#' @importFrom magclass setNames mbind
reportClimate <- function(
  gdx,
  output
) {
  # Try reading climate asessment data from GDX, but fail silently if none are available. If output is provided, match
  # the dimensions of the climate assessment variables individually to the output object. This is only necessary for
  # legacy reasons, as there is one single test case in which these variables have different dimensions.
  pm_globalMeanTemperature <- readGDX(gdx, "pm_globalMeanTemperature", react = "silent", restore_zeros = FALSE)
  if (!is.null(pm_globalMeanTemperature)) {
    pm_globalMeanTemperature <- setNames(pm_globalMeanTemperature, "Temperature|Global Mean (K)")
    pm_globalMeanTemperature <- matchYears(pm_globalMeanTemperature, output, fill = NA)
    pm_globalMeanTemperature <- matchRegions(pm_globalMeanTemperature, output, fill = NA)
  } else {
    message("reportClimate.R: pm_globalMeanTemperature not found in GDX file.")
  }
  p15_forc_magicc <- readGDX(gdx, "p15_forc_magicc", react = "silent", restore_zeros = FALSE)
  if (!is.null(p15_forc_magicc)) {
    p15_forc_magicc <- setNames(p15_forc_magicc, "Forcing (W/m2)")
    p15_forc_magicc <- matchYears(p15_forc_magicc, output, fill = NA)
    p15_forc_magicc <- matchRegions(p15_forc_magicc, output, fill = NA)
  } else {
    message("reportClimate.R: p15_forc_magicc not found in GDX file.")
  }

  # Combine climate assessment variables into one object, then return
  return(mbind(pm_globalMeanTemperature, p15_forc_magicc))
}
