#' Add SDP variables to mif, used in convGDX2MIF.R for the reporting
#'
#'
#'
#' @param gdx a GDX as created by readGDX, or the file name of a gdx
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' @param t temporal resolution of the reporting
#'
#' @return MAgPIE object - contains the SDP
#' @author Sebastian Rauner
#' @seealso \code{\link{convGDX2MIF}}
#' @examples
#'
#' \dontrun{reportSDPVariables(gdx, output, t)}
#'
#' @export
#'
#'
#' @importFrom magclass setNames mbind mselect
#' @importFrom dplyr filter



reportSDPVariables <- function(
  gdx,
  output = NULL,
  t = c(seq(2005, 2060, 5), seq(2070, 2110, 10), 2130, 2150)
) {

  # Define current realisation for the different modules
  module2realisation <- readGDX(gdx, "module2realisation")
  rownames(module2realisation) <- module2realisation$modules

  find_real_module <- function(module_set, module_name){
    return(module_set[module_set$modules == module_name,2])
  }

  tran_mod = find_real_module(module2realisation,"transport")
  indu_mod = find_real_module(module2realisation,"industry")
  buil_mod = find_real_module(module2realisation,"buildings")
  cdr_mod  = find_real_module(module2realisation,"CDR")
  CCU_mod  = find_real_module(module2realisation,"CCU")

  '%!in%' <- function(x,y)!('%in%'(x,y))

  addUEperCapForTransport <- function(output){

    if (tran_mod != "complex") # transport passengers FE variables used in this function are only available right now with the transport complex realization. Remove this conditional once either this function is rewritten or the variables are added to other module realisations.
      return()

    tmp <- NULL

    tmp <- mbind(
      if("UE|per capita|Transport|Pass (GJ/cap/yr)" %!in% getNames(output)){
      setNames(
        1e3 * (output[,,"FE|Transport|Pass|+|Liquids (EJ/yr)"] * 0.23
               + output[,,"FE|Transport|Pass|+|Electricity (EJ/yr)"] * 0.64
               + output[,,"FE|Transport|Pass|+|Hydrogen (EJ/yr)"] * 0.36)
        / output[,,"Population (million)"],
        "UE|per capita|Transport|Pass (GJ/cap/yr)")},

      if("UE|per capita|Transport (GJ/cap/yr)" %!in% getNames(output)){
      setNames(
        1e3 * (output[,,"FE|Transport|+|Liquids (EJ/yr)"] * 0.23
               + output[,,"FE|Transport|+|Electricity (EJ/yr)"] * 0.64
               + output[,,"FE|Transport|+|Hydrogen (EJ/yr)"] * 0.36)
        / output[,,"Population (million)"],
        "UE|per capita|Transport (GJ/cap/yr)")},

      if("Intensity|Final Energy|Useful Energy|Transport (-)" %!in% getNames(output)){
      setNames(
        (output[,,"FE|Transport|+|Liquids (EJ/yr)"]
         + output[,,"FE|Transport|+|Electricity (EJ/yr)"]
         + output[,,"FE|Transport|+|Hydrogen (EJ/yr)"])
        / (output[,,"FE|Transport|+|Liquids (EJ/yr)"] * 0.23
           + output[,,"FE|Transport|+|Electricity (EJ/yr)"] * 0.64
           + output[,,"FE|Transport|+|Hydrogen (EJ/yr)"] * 0.36),
        "Intensity|Final Energy|Useful Energy|Transport (-)")},

      if("UE|Electricity and Hydrogen|Share|Transport (%)" %!in% getNames(output)){
      setNames(
        1e2*(output[,,"FE|Transport|+|Electricity (EJ/yr)"] * 0.64
             + output[,,"FE|Transport|+|Hydrogen (EJ/yr)"] * 0.36)
        / (output[,,"FE|Transport|+|Liquids (EJ/yr)"] * 0.23
           + output[,,"FE|Transport|+|Electricity (EJ/yr)"] * 0.64
           + output[,,"FE|Transport|+|Hydrogen (EJ/yr)"] * 0.36),
        "UE|Electricity and Hydrogen|Share|Transport (%)")},

      if("UE|Electricity and Hydrogen|Share|Transport|Pass (%)" %!in% getNames(output)){
      setNames(
        1e2*(output[,,"FE|Transport|Pass|+|Electricity (EJ/yr)"] * 0.64
             + output[,,"FE|Transport|Pass|+|Hydrogen (EJ/yr)"] * 0.36)
        / (output[,,"FE|Transport|Pass|+|Liquids (EJ/yr)"] * 0.23
           + output[,,"FE|Transport|Pass|+|Electricity (EJ/yr)"] * 0.64
           + output[,,"FE|Transport|Pass|+|Hydrogen (EJ/yr)"] * 0.36),
        "UE|Electricity and Hydrogen|Share|Transport|Pass (%)")},

      if("Intensity|GDP|Final Energy|Transport (MJ/US$2005)" %!in% getNames(output)){
      setNames(
        1e3*(output[,,"FE|Transport|+|Electricity (EJ/yr)"]
             + output[,,"FE|Transport|+|Liquids (EJ/yr)"]
             + output[,,"FE|Transport|+|Hydrogen (EJ/yr)"])
        / output[,,"GDP|MER (billion US$2005/yr)"],
        "Intensity|GDP|Final Energy|Transport (MJ/US$2005)")},

      if("Intensity|GDP|Useful Energy|Transport (MJ/US$2005)" %!in% getNames(output)){
      setNames(
        1e3 * (output[,,"FE|Transport|Pass|+|Liquids (EJ/yr)"] * 0.23
               + output[,,"FE|Transport|Pass|+|Electricity (EJ/yr)"] * 0.64
               + output[,,"FE|Transport|Pass|+|Hydrogen (EJ/yr)"] * 0.36)
        / output[,,"GDP|MER (billion US$2005/yr)"],
        "Intensity|GDP|Useful Energy|Transport (MJ/US$2005)")})


    return(tmp)


  }


  addIndustry_UE_from_FE <- function(output) {

    tmp <- mbind(
      if("UE|Industry|Solids (EJ/yr)" %!in% getNames(output)){
      setNames(
        output[, , "FE|Industry|+|Solids (EJ/yr)"] / 1.95902175,
        "UE|Industry|Solids (EJ/yr)")},

      if("UE|Industry|Liquids (EJ/yr)" %!in% getNames(output)){
      setNames(
        output[, , "FE|Industry|+|Liquids (EJ/yr)"] / 2.484320995,
        "UE|Industry|Liquids (EJ/yr)")},

      if("UE|Industry|Gases (EJ/yr)" %!in% getNames(output)){
      setNames(
        output[, , "FE|Industry|+|Gases (EJ/yr)"] / 1.931690542,
        "UE|Industry|Gases (EJ/yr)")},

      if("UE|Industry|Hydrogen (EJ/yr)" %!in% getNames(output)){
      setNames(
        output[, , "FE|Industry|+|Hydrogen (EJ/yr)"] / 1.931690542,
        "UE|Industry|Hydrogen (EJ/yr)")},

      if("UE|Industry|Heat (EJ/yr)" %!in% getNames(output)){
      setNames(
        output[, , "FE|Industry|+|Heat (EJ/yr)"] / 1.572467703,
        "UE|Industry|Heat (EJ/yr)")},

      if("UE|Industry|Electricity (EJ/yr)" %!in% getNames(output)){
      setNames(
        output[, , "FE|Industry|+|Electricity (EJ/yr)"] / 1.824715164,
        "UE|Industry|Electricity (EJ/yr)")}
      )


    tmp <- mbind(
      tmp,
      if("UE|Industry (EJ/yr)" %!in% getNames(output)){
      setNames(
        tmp[, , "UE|Industry|Solids (EJ/yr)"]
        + tmp[, , "UE|Industry|Liquids (EJ/yr)"]
        + tmp[, , "UE|Industry|Gases (EJ/yr)"]
        + tmp[, , "UE|Industry|Hydrogen (EJ/yr)"]
        + tmp[, , "UE|Industry|Heat (EJ/yr)"]
        + tmp[, , "UE|Industry|Electricity (EJ/yr)"],
        "UE|Industry (EJ/yr)")})

    tmp <- mbind(
      tmp,
      if("UE|per capita|Industry (GJ/cap/yr)" %!in% getNames(output)){
      setNames(
        tmp[, , "UE|Industry (EJ/yr)"] / output[, , "Population (million)"] * 1e3,
        "UE|per capita|Industry (GJ/cap/yr)")})


    return(tmp)
  }


  addUEperCapForBuildings <- function(output){

    p36_uedemand_build <- readGDX(gdx, "p36_uedemand_build", react = "silent")[, t, ]
    if (buil_mod == "simple" & is.null(p36_uedemand_build)) #UE|Buildings var does not exist in this case
      return()

    tmp <- NULL

    tmp <- mbind(
      if("UE|per capita|Buildings (GJ/cap/yr)" %!in% getNames(output)){
        setNames(
          output[,,"UE|Buildings (EJ/yr)"]
          / output[,,"Population (million)"] * 1e3,
          "UE|per capita|Buildings (GJ/cap/yr)")})


    return(tmp)


  }


  #SDG|SDG07|Intensity|GDP|UE
  addIntensityUE <- function(output){

    vars <- c("UE|per capita|Transport (GJ/cap/yr)","UE|per capita|Industry (GJ/cap/yr)","UE|per capita|Buildings (GJ/cap/yr)","Population (million)","GDP|MER (billion US$2005/yr)")
    if(!(all(vars %in% getNames(output)))) # required variables not found
      return()

    tmp <- mbind(
  if("Intensity|GDP|UE (MJ/US$2005)" %!in% getNames(output)){
      setNames(
        ((output[,,"UE|per capita|Transport (GJ/cap/yr)"] + output[,,"UE|per capita|Industry (GJ/cap/yr)"]+ output[,,"UE|per capita|Buildings (GJ/cap/yr)"]) / 1e3 *output[,,"Population (million)"]) / (output[,,"GDP|MER (billion US$2005/yr)"] * 1e9),
        "Intensity|GDP|UE (MJ/US$2005)")})

    return(tmp)
  }


  output <- mbind(output,addUEperCapForTransport(output))
  output <- mbind(output,addIndustry_UE_from_FE(output))
  output <- mbind(output,addUEperCapForBuildings(output))
  output <- mbind(output,addIntensityUE(output))


  return(output)
}
