#' Read in GDX and calculate prices, used in convGDX2MIF.R for the reporting
#'
#' Read in price information from GDX file, information used in convGDX2MIF.R
#' for the reporting
#'
#'
#' @param gdx a GDX object as created by readGDX, or the path to a gdx
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' @param regionSubsetList a list containing regions to create report variables region
#' aggregations. If NULL (default value) only the global region aggregation "GLO" will
#' be created.
#' @param t temporal resolution of the reporting, default:
#' t=c(seq(2005,2060,5),seq(2070,2110,10),2130,2150)
#'
#' @return MAgPIE object - contains the price variables
#' @author Alois Dirnaichner, Felix Schreyer, David Klein, Renato Rodrigues, Falk Benke
#' @seealso \code{\link{convGDX2MIF}}
#' @examples
#'
#' \dontrun{reportPrices(gdx)}
#'
#' @importFrom luscale speed_aggregate
#' @importFrom dplyr %>% case_when distinct filter inner_join tibble left_join rename
#' @importFrom gdx readGDX
#' @importFrom magclass mbind getYears getRegions setNames dimSums new.magpie lowpass complete_magpie getItems<- getNames
#' @importFrom quitte df.2.named.vector getColValues
#' @importFrom readr read_csv
#' @importFrom madrat toolAggregate
#'

#' @export
reportPrices <- function(gdx, output=NULL, regionSubsetList=NULL,
                         t=c(seq(2005,2060,5),seq(2070,2110,10),2130,2150)) {

  ####### get realisations #########
  realisation <- readGDX(gdx, "module2realisation")

  ####### conversion factors ##########
  s_GWP_CH4 <- readGDX(gdx, c("sm_gwpCH4","s_gwpCH4","s_GWP_CH4"), format="first_found", react = "silent")
  s_GWP_N2O <- readGDX(gdx, c("s_gwpN2O","s_GWP_N2O"), format="first_found", react = "silent")
  s_twa2mwh <- readGDX(gdx, "sm_TWa_2_MWh", format = "first_found", reacht = "silent")
  tdptwyr2dpgj <- 31.71   #TerraDollar per TWyear to Dollar per GJ
  p80_subset   <- c("perm", "good", "peur", "peoil", "pegas", "pecoal", "pebiolc") #TODO: read in from gdx as sets trade
  ####### read in needed data #########

  #---- Functions
  find_real_module <- function(module_set, module_name){
    return(module_set[module_set$modules == module_name, 2])
  }

  indu_mod = find_real_module(realisation,"industry")

  ## parameter
  shift_p        <- readGDX(gdx,name="p30_pebiolc_pricshift",format="first_found")[, t,]
  mult_p         <- readGDX(gdx,name="p30_pebiolc_pricmult",format="first_found")[, t,]
  pric_mag       <- readGDX(gdx,name="p30_pebiolc_pricemag",format="first_found")[, t,]
  pric_emu_pre   <- readGDX(gdx,name="p30_pebiolc_price_emu_preloop",format="first_found")[, t,]
  pric_emu_pre_shifted <- readGDX(gdx,name="p30_pebiolc_price_emu_preloop_shifted",format="first_found")[, t,]
  bio_tax_factor <- readGDX(gdx,name="p21_tau_bioenergy_tax",format="first_found")[, t,]
  pm_pvp         <- readGDX(gdx,name=c("pm_pvp","p80_pvp"),format="first_found")[, t, p80_subset]
  pm_dataemi     <- readGDX(gdx,name=c("pm_emifac","pm_dataemi"),format="first_found",restore_zeros=FALSE)[,t, c("pegas.seel.ngt.co2","pecoal.seel.pc.co2")]
  pm_pvpRegi     <- readGDX(gdx,name='pm_pvpRegi',format="first_found")[, t, "perm"]
  pm_taxCO2eq    <- readGDX(gdx,name=c("pm_taxCO2eq","pm_tau_CO2_tax"),format="first_found")[, t,]
  pm_taxCO2eqSCC <- readGDX(gdx,name='pm_taxCO2eqSCC',format="first_found")[, t,]
  p21_CO2TaxSectorMarkup <- readGDX(gdx,name=c('p21_CO2TaxSectorMarkup','p21_CO2_tax_sector_markup'),format="first_found",react="silent")
  pm_taxemiMkt   <- readGDX(gdx,name="pm_taxemiMkt",format="first_found")[, t,]
  ## variables
  pric_emu       <- readGDX(gdx,name="vm_pebiolc_price",field="l",format="first_found")[, t,]

  ## equations
  budget.m       <- readGDX(gdx,name='qm_budget',types = "equations",field = "m",format = "first_found")[, t,] # Alternative: calcPrice
  balcapture.m   <- readGDX(gdx,name=c("q_balcapture", "q12_balcapture"), field = "m", restore_zeros = F)[, t,]

  esm2macro.m    <- readGDX(gdx,name='q35_esm2macro',types="equations",field="m",format="first_found", react = "silent")[, t,]

  cm_emiscen     <- readGDX(gdx,name='cm_emiscen',format="first_found")

  q37_limit_secondary_steel_share.m <- readGDX(
    gdx, name = 'q37_limit_secondary_steel_share', types = 'equation',
    field = 'm', react = 'silent')[, t,]

  #####################################
  #choose the CES entries names for transport
  if (!is.null(esm2macro.m)) {
    name_trsp=c("fepet","ueLDVt","fedie","ueHDVt","feelt","ueelTt")
    name_trsp=name_trsp[name_trsp%in%getNames(esm2macro.m)]
  }
  #####################################

  ####### pm_pvp = EPS results in fantasy carbon prices

  for(yr in getYears(pm_pvp)){
    if(pm_pvp[,yr,"good"] == 0){
      pm_pvp[,yr,"good"] = 0.0001;
    }
  }

  module2realisation <- readGDX(gdx, "module2realisation")
  rownames(module2realisation) <- module2realisation$modules


  pm_FEPrice <- readGDX(gdx, "pm_FEPrice")
  pm_SEPrice <- readGDX(gdx, "pm_SEPrice")
  pm_PEPrice <- readGDX(gdx, c("p_PEPrice", "pm_PEPrice"), format = "first_found")


  vm_demFeSector <- readGDX(gdx, "vm_demFeSector", field = "l", restore_zeros = FALSE)[,t,]
  prodSe         <- readGDX(gdx, "vm_prodSe", field = "l", restore_zeros = FALSE)[,t,]
  try(seAgg <- readGDX(gdx, name="seAgg", type="set"))
  try(seAgg2se <- readGDX(gdx, name="seAgg2se", type="set"))




  # subset price parameters to those entries used in the model
  pe2se <- readGDX(gdx, "pe2se")
  se2fe <- readGDX(gdx, "se2fe")
  sector2emiMkt <- readGDX(gdx, "sector2emimkt")
  entyFe2Sector <- readGDX(gdx, "entyFe2Sector")


  sector <- emi_sectors <- emiMkt <- all_emiMkt <- NULL
  fe.entries <- entyFe2Sector %>%
                  left_join(sector2emiMkt) %>%
                  rename( sector = emi_sectors, emiMkt = all_emiMkt) %>%
                  filter( sector != "CDR")


  fe.entries.dot <- paste(fe.entries[,1],fe.entries[,2], fe.entries[,3], sep = ".")

  ttot <- readGDX(gdx, "ttot")
  YearsFrom2005 <- paste0("y",ttot[ttot >= 2005])

  pm_PEPrice <- pm_PEPrice[,YearsFrom2005,unique(pe2se$all_enty)]
  pm_SEPrice <- pm_SEPrice[,YearsFrom2005,unique(se2fe$all_enty)]
  pm_FEPrice <- pm_FEPrice[,YearsFrom2005,fe.entries.dot]


  ## weights for market aggregation of prices: FE share of market
  p_weights_FEprice_mkt <- dimSums(vm_demFeSector, dim=3.1, na.rm = T) / dimSums(vm_demFeSector, dim=c(3.1,3.4), na.rm = T)
  p_weights_FEprice_mkt[is.na(p_weights_FEprice_mkt)] <- 0
  ## adjust to pm_FEprice dimensions
  p_weights_FEprice_mkt <- p_weights_FEprice_mkt[,getYears(pm_FEPrice),getNames(pm_FEPrice)]

  ## weights for fepet/fedie to liquids aggregation of prices: FE fepet/fedie share of aggregated markets
  p_weights_FEprice_diepet <- dimSums(mselect(vm_demFeSector, all_enty1=c("fedie","fepet"), emi_sectors="trans"), dim=c(3.1,3.4), na.rm = T) /
    dimSums(mselect(vm_demFeSector, all_enty1=c("fedie","fepet"), emi_sectors="trans"), dim=c(3.1,3.2,3.4), na.rm = T)
  p_weights_FEprice_diepet[is.na(p_weights_FEprice_diepet)] <- 0
  p_weights_FEprice_diepet <- p_weights_FEprice_diepet[,getYears(pm_FEPrice),]

  out <- NULL

  ## calculate prices as weighted average prices across markets
  ## FE Transport Prices
  out <- mbind(
    out,
    setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="feelt", emi_sectors = "trans"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
             "Price|Final Energy|Transport|Electricity (US$2005/GJ)"),
    ## in case of transport liquids: calculate weighted average of markets first, then calculate weighted average of fepet/fedie
    setNames( dimSums( p_weights_FEprice_diepet * dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1=c("fepet","fedie"), emi_sectors = "trans"), dim=3.3, na.rm = T), dim=3.1, na.rm = T)*tdptwyr2dpgj,
             "Price|Final Energy|Transport|Liquids (US$2005/GJ)"),
    setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="feh2t", emi_sectors = "trans"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
             "Price|Final Energy|Transport|Hydrogen (US$2005/GJ)")
  )

  if (module2realisation["transport",2] == "edge_esm") {
    out <- mbind(
      out,
      setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fegat", emi_sectors = "trans"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
               "Price|Final Energy|Transport|Gases (US$2005/GJ)"))
  }

  out <- mbind(
    out,
    setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fedie", emi_sectors = "trans"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
             "Price|Final Energy|Transport|Liquids|HDV (US$2005/GJ)"),
    setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fepet", emi_sectors = "trans"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
             "Price|Final Energy|Transport|Liquids|LDV (US$2005/GJ)"))

  ## FE Buildings Prices
  out <- mbind(out,
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="feels", emi_sectors = "build"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Buildings|Electricity (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fegas", emi_sectors = "build"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Buildings|Gases (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="feh2s", emi_sectors = "build"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Buildings|Hydrogen (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fehos", emi_sectors = "build"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Buildings|Liquids (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fehes", emi_sectors = "build"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Buildings|Heat (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fesos", emi_sectors = "build"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Buildings|Solids (US$2005/GJ)")
               )

  ## FE Industry Prices
  out <- mbind(out,
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="feels", emi_sectors = "indst"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Industry|Electricity (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fegas", emi_sectors = "indst"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Industry|Gases (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="feh2s", emi_sectors = "indst"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Industry|Hydrogen (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fehos", emi_sectors = "indst"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Industry|Liquids (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fehes", emi_sectors = "indst"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Industry|Heat (US$2005/GJ)"),
               setNames( dimSums(mselect(p_weights_FEprice_mkt * pm_FEPrice, all_enty1="fesos", emi_sectors = "indst"), dim=3.3, na.rm = T)*tdptwyr2dpgj,
                        "Price|Final Energy|Industry|Solids (US$2005/GJ)")
               )

  ## SE Prices
  out <- mbind(out,
               setNames(mselect(pm_SEPrice, all_enty="seliqfos")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Liquids|Fossil (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="seliqbio")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Liquids|Biomass (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="seliqsyn")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Liquids|Hydrogen (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="sesobio")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Solids|Biomass (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="sesofos")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Solids|Fossil (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="seel")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Electricity (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="seh2")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Hydrogen (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="segabio")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Gases|Biomass (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="segafos")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Gases|Fossil (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="segasyn")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Gases|Hydrogen (US$2005/GJ)"),
               setNames(mselect(pm_SEPrice, all_enty="sehe")*tdptwyr2dpgj,
                        "Price|Secondary Energy|Heat (US$2005/GJ)")
               )
  weightsSe <- NULL
  if (exists("seAgg")) {
    for (i in seAgg) { # calculate weights based on SE production shares, for all possible secondary energy aggregations (set seAgg in REMIND code)
      weightsSe <- mbind(weightsSe,dimSums(mselect(prodSe, all_enty1=unique(filter(seAgg2se ,.data$all_enty==i)[,"all_enty1"])),dim=c(3.1,3.3),na.rm=T)/
                           dimSums(mselect(prodSe, all_enty1=filter(seAgg2se ,.data$all_enty==i)[,"all_enty1"])                       ,na.rm=T))
    }
    weightsSe <- weightsSe[,intersect(getYears(weightsSe),getYears(pm_SEPrice)),intersect(getItems(weightsSe,dim=3),getItems(pm_SEPrice,dim=3))]
    out <- mbind(out,
                 setNames(dimSums(mselect(weightsSe*pm_SEPrice[,,getItems(weightsSe,dim=3)], all_enty1=unique(filter(seAgg2se ,.data$all_enty=="all_seliq")[,"all_enty1"])))*tdptwyr2dpgj,
                          "Price|Secondary Energy|Liquids (US$2005/GJ)"),
                 setNames(dimSums(mselect(weightsSe*pm_SEPrice[,,getItems(weightsSe,dim=3)], all_enty1=unique(filter(seAgg2se ,.data$all_enty=="all_seso")[,"all_enty1"])))*tdptwyr2dpgj,
                          "Price|Secondary Energy|Solids (US$2005/GJ)"),
                 setNames(dimSums(mselect(weightsSe*pm_SEPrice[,,getItems(weightsSe,dim=3)], all_enty1=unique(filter(seAgg2se ,.data$all_enty=="all_sega")[,"all_enty1"])))*tdptwyr2dpgj,
                          "Price|Secondary Energy|Gases (US$2005/GJ)")
    )
  }


  ## PE Prices
  out <- mbind(out,
               setNames(mselect(pm_PEPrice, all_enty="peoil")*tdptwyr2dpgj,
                        "Price|Primary Energy|Oil (US$2005/GJ)"),
               setNames(mselect(pm_PEPrice, all_enty="pegas")*tdptwyr2dpgj,
                        "Price|Primary Energy|Gas (US$2005/GJ)"),
               setNames(mselect(pm_PEPrice, all_enty="pecoal")*tdptwyr2dpgj,
                        "Price|Primary Energy|Coal (US$2005/GJ)"),
               setNames(mselect(pm_PEPrice, all_enty="peur")*tdptwyr2dpgj,
                        "Price|Primary Energy|Nuclear (US$2005/GJ)"),
               ## only modern (ligno-cellulosic) biomass reported
               setNames(mselect(pm_PEPrice, all_enty="pebiolc")*tdptwyr2dpgj,
                        "Price|Primary Energy|Biomass|Modern (US$2005/GJ)"),
               setNames(mselect(pm_PEPrice, all_enty="pebios")*tdptwyr2dpgj,
                        "Price|Primary Energy|Biomass|1st Generation|Sugar and Starch (US$2005/GJ)"),
               setNames(mselect(pm_PEPrice, all_enty="pebios")*tdptwyr2dpgj,
                        "Price|Primary Energy|Biomass|1st Generation|Oil-based (US$2005/GJ)")
               )

  ## detailed FE price calculations ----
  
  ### Transport and Distribution Cost ----
  
  tech <- c(
    "tdfospet", "tdfosdie", "tdbiopet", "tdsynpet", "tdsyngas", "tdfosgas", "tdfosgat", "tdfossos",
    "tdh2t", "tdelt", "tdels", "tdhes", "tdbiosos", "tdbiogas", "tdh2s", "tdfoshos", "tdsyngat"
  )
  
  vm_costTeCapital <- readGDX(gdx, "vm_costTeCapital", field = "l", restore_zeros = F)[, YearsFrom2005, tech] # [tr USD2005/TWh]
  p_teAnnuity <- readGDX(gdx, "p_teAnnuity", restore_zeros = F)[, , tech]
  vm_capFac <- readGDX(gdx, "vm_capFac", field = "l", restore_zeros = F)[, YearsFrom2005, tech] * 8760
  pm_data_omf <- readGDX(gdx, "pm_data", restore_zeros = F)[, , "omf"][, , tech]
  
  price.investment <- vm_costTeCapital * p_teAnnuity / vm_capFac
  price.omf <- pm_data_omf * vm_costTeCapital / vm_capFac
  price.td <- collapseDim(price.investment + price.omf)  * 1e6 / 3.6 # [tr USD2005/TWh] -> [USD2005/GJ]
  
  out <- mbind(
    out, 
    setNames(price.td[, , "tdfospet"], "Price|Final Energy|Transport|Liquids|Petroleum|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdfosdie"], "Price|Final Energy|Transport|Liquids|Diesel|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdbiopet"], "Price|Final Energy|Transport|Liquids|Biomass|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdsynpet"], "Price|Final Energy|Transport|Liquids|Efuel|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdsyngat"], "Price|Final Energy|Transport|Gases|Efuel|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdfosgat"], "Price|Final Energy|Transport|Gases|Natural Gas|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdh2t"], "Price|Final Energy|Transport|Hydrogen|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdelt"], "Price|Final Energy|Transport|Electricity|Transport and Distribution (US$2005/GJ)"),
    
    setNames(price.td[, , "tdfoshos"], "Price|Final Energy|Buildings|Liquids|Oil|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdfosgas"], "Price|Final Energy|Buildings|Gases|Natural Gas|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdhes"], "Price|Final Energy|Buildings|Heat|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdbiopet"], "Price|Final Energy|Buildings|Liquids|Biomass|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdbiosos"], "Price|Final Energy|Buildings|Solids|Biomass|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdbiogas"], "Price|Final Energy|Buildings|Gases|Biomass|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdsynpet"], "Price|Final Energy|Buildings|Liquids|Efuel|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdsyngas"], "Price|Final Energy|Buildings|Gases|Efuel|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdh2s"], "Price|Final Energy|Buildings|Hydrogen|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdels"], "Price|Final Energy|Buildings|Electricity|Transport and Distribution (US$2005/GJ)"),
    
    setNames(price.td[, , "tdfoshos"], "Price|Final Energy|Industry|Liquids|Oil|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdfossos"], "Price|Final Energy|Industry|Solids|Coal|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdfosgas"], "Price|Final Energy|Industry|Gases|Natural Gas|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdhes"], "Price|Final Energy|Industry|Heat|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdbiopet"], "Price|Final Energy|Industry|Liquids|Biomass|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdbiosos"], "Price|Final Energy|Industry|Solids|Biomass|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdbiogas"], "Price|Final Energy|Industry|Gases|Biomass|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdsynpet"], "Price|Final Energy|Industry|Liquids|Efuel|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdsyngas"], "Price|Final Energy|Industry|Gases|Efuel|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdh2s"], "Price|Final Energy|Industry|Hydrogen|Transport and Distribution (US$2005/GJ)"),
    setNames(price.td[, , "tdels"], "Price|Final Energy|Industry|Electricity|Transport and Distribution (US$2005/GJ)")
  )
  
  
  
  
  
  
  ### Carbon Price Component ----
  
  tech.fossil <- c("tdfospet", "tdfosdie", "tdfosgas", "tdfoshos", "tdfossos")
  pm_emifac <- readGDX(gdx, "pm_emifac", field = "l", restore_zeros = F)[, YearsFrom2005, "co2"][, , tech.fossil] # [GtC CO2/TWa]
  pm_emifac <- pm_emifac * 1e9 / s_twa2mwh / 3.6 # [GtC CO2/TWa] -> [tC CO2/GJ]
  
  pm_priceCO2 <- readGDX(gdx, "pm_priceCO2", restore_zeros = F) # [USD2005/tC CO2]
  pm_priceCO2 <- add_columns(pm_priceCO2, addnm = setdiff(YearsFrom2005, getYears(pm_priceCO2)), dim = 2, fill = NA)
  
  price.carbon <- collapseDim(pm_emifac * pm_priceCO2) # [USD2005/GJ]
  
  out <- mbind(
    out, 
    setNames(price.carbon[, , "tdfospet"], "Price|Final Energy|Transport|Liquids|Petroleum|Carbon Price Component (US$2005/GJ)"),
    setNames(price.carbon[, , "tdfosdie"], "Price|Final Energy|Transport|Liquids|Diesel|Carbon Price Component (US$2005/GJ)"),
    setNames(price.carbon[, , "tdfosgas"], "Price|Final Energy|Transport|Gases|Natural Gas|Carbon Price Component (US$2005/GJ)"),
    
    setNames(price.carbon[, , "tdfoshos"], "Price|Final Energy|Buildings|Liquids|Oil|Carbon Price Component (US$2005/GJ)"),
    setNames(price.carbon[, , "tdfosgas"], "Price|Final Energy|Buildings|Gases|Natural Gas|Carbon Price Component (US$2005/GJ)"),
    
    setNames(price.carbon[, , "tdfoshos"], "Price|Final Energy|Industry|Liquids|Oil|Carbon Price Component (US$2005/GJ)"),
    setNames(price.carbon[, , "tdfossos"], "Price|Final Energy|Industry|Solids|Coal|Carbon Price Component (US$2005/GJ)"),
    setNames(price.carbon[, , "tdfosgas"], "Price|Final Energy|Industry|Gases|Natural Gas|Carbon Price Component (US$2005/GJ)")
  )
  
  
  
  ### Tax Component ----
  entyFe2Sector <- c(
    "trans.fepet", "trans.fedie", "trans.feelt", "trans.feh2t", "trans.fegat",
    "build.fehos", "build.fesos", "build.feels", "build.feh2s", "build.fegas",
    "indst.fehos", "indst.fesos", "indst.feels", "indst.feh2s", "indst.fegas",
    "build.fepet", "indst.fepet"
  )
  pm_tau_fe_tax <- readGDX(gdx, "pm_tau_fe_tax")[, YearsFrom2005, entyFe2Sector] # [tr USD2005/TWa]
  pm_tau_fe_sub <- readGDX(gdx, "pm_tau_fe_sub")[, YearsFrom2005, entyFe2Sector] # [tr USD2005/TWa]
  price.tax <- (pm_tau_fe_tax + pm_tau_fe_sub) / s_twa2mwh / 3.6 * 1e12 # [USD2005/GJ]
  
  out <- mbind(
    out, 
    setNames(price.tax[, , "trans.fepet"], "Price|Final Energy|Transport|Liquids|Petroleum|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "trans.fedie"], "Price|Final Energy|Transport|Liquids|Diesel|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "trans.fegat"], "Price|Final Energy|Transport|Gases|Natural Gas|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "trans.fepet"], "Price|Final Energy|Transport|Liquids|Biomass|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "trans.fepet"], "Price|Final Energy|Transport|Liquids|Efuel|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "trans.fegat"], "Price|Final Energy|Transport|Gases|Efuel|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "trans.feh2t"], "Price|Final Energy|Transport|Hydrogen|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "trans.feelt"], "Price|Final Energy|Transport|Electricity|Other Taxes (US$2005/GJ)"),
    
    setNames(price.tax[, , "build.fehos"], "Price|Final Energy|Buildings|Liquids|Oil|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.fegas"], "Price|Final Energy|Buildings|Gases|Natural Gas|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.fehos"], "Price|Final Energy|Buildings|Heat|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.fepet"], "Price|Final Energy|Buildings|Liquids|Biomass|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.fesos"], "Price|Final Energy|Buildings|Solids|Biomass|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.fegas"], "Price|Final Energy|Buildings|Gases|Biomass|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.fepet"], "Price|Final Energy|Buildings|Liquids|Efuel|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.fegas"], "Price|Final Energy|Buildings|Gases|Efuel|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.feh2s"], "Price|Final Energy|Buildings|Hydrogen|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "build.feels"], "Price|Final Energy|Buildings|Electricity|Other Taxes (US$2005/GJ)"),
    
    setNames(price.tax[, , "indst.fehos"], "Price|Final Energy|Industry|Liquids|Oil|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.fesos"], "Price|Final Energy|Industry|Solids|Coal|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.fegas"], "Price|Final Energy|Industry|Gases|Natural Gas|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.fehos"], "Price|Final Energy|Industry|Heat|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.fepet"], "Price|Final Energy|Industry|Liquids|Biomass|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.fesos"], "Price|Final Energy|Industry|Solids|Biomass|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.fegas"], "Price|Final Energy|Industry|Gases|Biomass|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.fepet"], "Price|Final Energy|Industry|Liquids|Efuel|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.fegas"], "Price|Final Energy|Industry|Gases|Efuel|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.feh2s"], "Price|Final Energy|Industry|Hydrogen|Other Taxes (US$2005/GJ)"),
    setNames(price.tax[, , "indst.feels"], "Price|Final Energy|Industry|Electricity|Other Taxes (US$2005/GJ)")
  )
  
  
  
  ### Fuel Cost Component ----
  
  se <- c("seliqfos", "segafos", "seliqbio", "segabio", "seliqsyn", "segasyn", "seh2", "seel", "sesofos", "sehe", "sesobio")
  pm_SEPrice <- readGDX(gdx, "pm_SEPrice")[, YearsFrom2005, se] / s_twa2mwh / 3.6 * 1e12 # [tr USD2005/TWa] -> [USD2005/GJ]
  pm_eta_conv <- readGDX(gdx, "pm_eta_conv", restore_zeros = F)[, YearsFrom2005, tech]
  price.fuel <- pm_SEPrice / pm_eta_conv
  
  out <- mbind(
    out,
    setNames(price.fuel[,,"seliqfos.tdfospet"], "Price|Final Energy|Transport|Liquids|Petroleum|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seliqfos.tdfosdie"], "Price|Final Energy|Transport|Liquids|Diesel|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"segafos.tdfosgat"], "Price|Final Energy|Transport|Gases|Natural Gas|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seliqbio.tdbiopet"], "Price|Final Energy|Transport|Liquids|Biomass|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seliqsyn.tdsynpet"], "Price|Final Energy|Transport|Liquids|Efuel|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"segasyn.tdsyngat"], "Price|Final Energy|Transport|Gases|Efuel|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seh2.tdh2t"], "Price|Final Energy|Transport|Hydrogen|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seel.tdelt"], "Price|Final Energy|Transport|Electricity|Fuel Cost (US$2005/GJ)"),
    
    setNames(price.fuel[,,"seliqfos.tdfoshos"], "Price|Final Energy|Buildings|Liquids|Oil|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"segafos.tdfosgas"], "Price|Final Energy|Buildings|Gases|Natural Gas|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"sehe.tdhes"], "Price|Final Energy|Buildings|Heat|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seliqbio.tdbiopet"], "Price|Final Energy|Buildings|Liquids|Biomass|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"sesobio.tdbiosos"], "Price|Final Energy|Buildings|Solids|Biomass|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"segabio.tdbiogas"], "Price|Final Energy|Buildings|Gases|Biomass|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seliqsyn.tdsynpet"], "Price|Final Energy|Buildings|Liquids|Efuel|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"segasyn.tdsyngas"], "Price|Final Energy|Buildings|Gases|Efuel|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seh2.tdh2s"], "Price|Final Energy|Buildings|Hydrogen|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seel.tdels"], "Price|Final Energy|Buildings|Electricity|Fuel Cost (US$2005/GJ)"),
    
    setNames(price.fuel[,,"seliqfos.tdfoshos"], "Price|Final Energy|Industry|Liquids|Oil|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"sesofos.tdfossos"], "Price|Final Energy|Industry|Solids|Coal|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"segafos.tdfosgas"], "Price|Final Energy|Industry|Gases|Natural Gas|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seliqbio.tdbiopet"], "Price|Final Energy|Industry|Liquids|Biomass|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"sesobio.tdbiosos"], "Price|Final Energy|Industry|Solids|Biomass|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"segabio.tdbiogas"], "Price|Final Energy|Industry|Gases|Biomass|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seliqsyn.tdsynpet"], "Price|Final Energy|Industry|Liquids|Efuel|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"segasyn.tdsyngas"], "Price|Final Energy|Industry|Gases|Efuel|Fuel Cost (US$2005/GJ)"),
    
    setNames(price.fuel[,,"seel.tdels"], "Price|Final Energy|Industry|Electricity|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"seh2.tdh2s"], "Price|Final Energy|Industry|Hydrogen|Fuel Cost (US$2005/GJ)"),
    setNames(price.fuel[,,"sehe.tdhes"], "Price|Final Energy|Industry|Heat|Fuel Cost (US$2005/GJ)")
  )
  
  ### Total LCOE ----
  
  .calcLCOE <- function(out, var) {
    return(setNames(dimSums(out[, , paste0(var,"|"), pmatch = T], dim = 3, na.rm = T), paste0(var, "|Total LCOE (US$2005/GJ)")))
  }
  
  out <- mbind(
    out,
    .calcLCOE(out, "Price|Final Energy|Transport|Liquids|Petroleum"),
    .calcLCOE(out, "Price|Final Energy|Transport|Liquids|Diesel"),
    .calcLCOE(out, "Price|Final Energy|Transport|Gases|Natural Gas"),
    .calcLCOE(out, "Price|Final Energy|Transport|Liquids|Biomass"),
    .calcLCOE(out, "Price|Final Energy|Transport|Liquids|Efuel"),
    .calcLCOE(out, "Price|Final Energy|Transport|Gases|Efuel"),
    .calcLCOE(out, "Price|Final Energy|Transport|Hydrogen"),
    .calcLCOE(out, "Price|Final Energy|Transport|Electricity"),
    
    .calcLCOE(out, "Price|Final Energy|Buildings|Liquids|Oil"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Gases|Natural Gas"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Heat"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Liquids|Biomass"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Solids|Biomass"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Gases|Biomass"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Liquids|Efuel"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Gases|Efuel"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Hydrogen"),
    .calcLCOE(out, "Price|Final Energy|Buildings|Electricity"),
    
    .calcLCOE(out, "Price|Final Energy|Industry|Liquids|Oil"),
    .calcLCOE(out, "Price|Final Energy|Industry|Solids|Coal"),
    .calcLCOE(out, "Price|Final Energy|Industry|Gases|Natural Gas"),
    .calcLCOE(out, "Price|Final Energy|Industry|Liquids|Biomass"),
    .calcLCOE(out, "Price|Final Energy|Industry|Solids|Biomass"),
    .calcLCOE(out, "Price|Final Energy|Industry|Gases|Biomass"),
    .calcLCOE(out, "Price|Final Energy|Industry|Liquids|Efuel"),
    .calcLCOE(out, "Price|Final Energy|Industry|Gases|Efuel"),
    .calcLCOE(out, "Price|Final Energy|Industry|Electricity"),
    .calcLCOE(out, "Price|Final Energy|Industry|Hydrogen"),
    .calcLCOE(out, "Price|Final Energy|Industry|Heat")
  )
  
  ## apply lowpass filter to receive moving average prices ----
  out.lowpass <- lowpass(out)
  ## add "Moving Avg" to variable name
  getNames(out.lowpass) <- paste0(substr(getNames(out.lowpass),
                                         1,nchar(getNames(out.lowpass))-13),
                                  "|Moving Avg",
                                  substr(getNames(out.lowpass),
                                         nchar(getNames(out.lowpass))-12,
                                         nchar(getNames(out.lowpass))))

  out <- mbind(out,out.lowpass)

  ## add years before cm_startyear (temporary, can be adapted once prices only calculated after cm_startyear in REMIND code)
  out2 <- new.magpie(getRegions(out), getYears(vm_demFeSector), getNames(out), fill = NA)
  out2[,getYears(out), ] <- out

  out <- out2

  # Calculate and append new variables to magpie object
  # Costs and prices for purpose-grown 2nd gen. bioenergy
  # - Shiftfactor
  # - imported values from MAgPIE reporting
  # - results from emulator based on MAgPIE demand (before main solve)
  # - results from emulator based on MAgPIE demand multiplied with shiftfactor (before main solve)
  # - results from emulator based on REMIND demand (after main solve)
  # - results from emulator based on REMIND demand multiplied with shiftfactor (after main solve)

  out <- mbind(
    out,
    setNames(shift_p, "Internal|Price|Biomass|Shiftfactor ()"),
    setNames(mult_p, "Internal|Price|Biomass|Multfactor ()"),
    setNames(pric_mag * tdptwyr2dpgj, "Internal|Price|Biomass|MAgPIE (US$2005/GJ)"),
    setNames(pric_emu_pre * tdptwyr2dpgj, "Internal|Price|Biomass|Emulator presolve (US$2005/GJ)"),
    setNames(pric_emu_pre_shifted * tdptwyr2dpgj, "Internal|Price|Biomass|Emulator presolve shifted (US$2005/GJ)"),
    setNames(pric_emu * tdptwyr2dpgj, "Internal|Price|Biomass|Emulator shifted (US$2005/GJ)"),
    setNames(pric_emu * bio_tax_factor * tdptwyr2dpgj, "Internal|Price|Biomass|Bioenergy tax (US$2005/GJ)"))


  # energy services
  if (!is.null(esm2macro.m)) {
    out <- mbind(
      out,
      setNames(abs(esm2macro.m[,,name_trsp[2]]/(budget.m+1e-10)) * tdptwyr2dpgj , "Price|Energy Service|Transport nonLDV (US$2005/GJ)"),
      setNames(abs(esm2macro.m[,,name_trsp[1]]/(budget.m+1e-10)) * tdptwyr2dpgj , "Price|Energy Service|Transport LDV (US$2005/GJ)"))
  }

  FE_data   <- reportFE(gdx, regionSubsetList = regionSubsetList, t = t)
  Emi_data <- reportEmi(gdx, regionSubsetList = regionSubsetList, t = t)
  FE_data_regi  <-  FE_data[getItems(pm_pvpRegi, dim = "all_regi"), , ] # get rid of GLO
  Emi_data_regi <- Emi_data[getItems(pm_pvpRegi, dim = "all_regi"), , ]

  # report GHG taxes, differentiated by sector
  if (all(p21_CO2TaxSectorMarkup == 0)) { # then all are identical
    out <- mbind(out, setNames(abs(pm_pvpRegi / (pm_pvp[,,"good"] + 1e-10)) * 1000 * 12/44, "Price|Carbon (US$2005/t CO2)"))
    for (pcname in c("Price|Carbon|Demand|Buildings (US$2005/t CO2)", "Price|Carbon|Demand|Transport (US$2005/t CO2)",
                     "Price|Carbon|Demand|Industry (US$2005/t CO2)", "Price|Carbon|Supply (US$2005/t CO2)",
                     "Price|Carbon|AggregatedByGrossCO2 (US$2005/t CO2)")) {
      out <- mbind(out, setNames(out[, , "Price|Carbon (US$2005/t CO2)"], pcname))
    }
  } else {  # currently p21_CO2TaxSectorMarkup is only implemented for build and trans in REMIND
    out <- mbind(out,
                 setNames((1 + p21_CO2TaxSectorMarkup[, , "build"]) * abs(pm_pvpRegi / (pm_pvp[,,"good"] + 1e-10)) * 1000 * 12/44,
                           "Price|Carbon|Demand|Buildings (US$2005/t CO2)"),
                 setNames((1 + p21_CO2TaxSectorMarkup[, , "trans"]) * abs(pm_pvpRegi / (pm_pvp[,,"good"] + 1e-10)) * 1000 * 12/44,
                           "Price|Carbon|Demand|Transport (US$2005/t CO2)"),
                 setNames(abs(pm_pvpRegi / (pm_pvp[,,"good"] + 1e-10)) * 1000 * 12/44,
                           "Price|Carbon|Demand|Industry (US$2005/t CO2)"),
                 setNames(abs(pm_pvpRegi / (pm_pvp[,,"good"] + 1e-10)) * 1000 * 12/44,
                           "Price|Carbon|Supply (US$2005/t CO2)")
                )
    pm_pvpRegi_FE <- pm_pvpRegi * (1 +
                                    (
                                       p21_CO2TaxSectorMarkup[, , "build"] * FE_data_regi[, , "FE|++|Buildings (EJ/yr)"]
                                     + p21_CO2TaxSectorMarkup[, , "trans"] * FE_data_regi[, , "FE|++|Transport (EJ/yr)"]
                                    ) / FE_data_regi[, , "FE (EJ/yr)"]
    )
    pm_pvpRegi_Emi <- pm_pvpRegi * (1 +
                                     (
                                         p21_CO2TaxSectorMarkup[, , "build"] * Emi_data_regi[, , "Emi|GHG|Gross|Energy|Demand|+|Buildings (Mt CO2eq/yr)"]
                                       + p21_CO2TaxSectorMarkup[, , "trans"] * Emi_data_regi[, , "Emi|GHG|Gross|Energy|Demand|+|Transport (Mt CO2eq/yr)"]
                                     ) / Emi_data_regi[, , "Emi|GHG|Gross|Energy (Mt CO2eq/yr)"]
    )
    out <- mbind(out, setNames(abs(pm_pvpRegi_FE  / (pm_pvp[,,"good"] + 1e-10)) * 1000 * 12/44,
                                "Price|Carbon (US$2005/t CO2)")) # AggregatedbyFE
    out <- mbind(out, setNames(abs(pm_pvpRegi_Emi / (pm_pvp[,,"good"] + 1e-10)) * 1000 * 12/44,
                                "Price|Carbon|AggregatedByGrossCO2 (US$2005/t CO2)")) # AggregatedByEmiGHGGross
  }

  # report GHG tax revenues
  out <- mbind(out,
               setNames(out[, , "Price|Carbon|Demand|Buildings (US$2005/t CO2)"] *  Emi_data_regi[, , "Emi|GHG|Energy|Demand|+|Buildings (Mt CO2eq/yr)"] / 1000,
                          "Revenue|Government|Tax|Carbon|+|Demand|Buildings (billion US$2005/yr)"),
               setNames(out[, , "Price|Carbon|Demand|Transport (US$2005/t CO2)"] *  Emi_data_regi[, , "Emi|GHG|Energy|Demand|+|Transport (Mt CO2eq/yr)"] / 1000,
                          "Revenue|Government|Tax|Carbon|+|Demand|Transport (billion US$2005/yr)"),
               setNames(out[, , "Price|Carbon|Demand|Industry (US$2005/t CO2)"]  * (Emi_data_regi[, , "Emi|GHG|Energy|Demand|+|Industry (Mt CO2eq/yr)"] + Emi_data_regi[, ,"Emi|CO2|+|Industrial Processes (Mt CO2/yr)"]) / 1000,
                          "Revenue|Government|Tax|Carbon|+|Demand|Industry (billion US$2005/yr)"),
               setNames(out[, , "Price|Carbon|Supply (US$2005/t CO2)"]           *  Emi_data_regi[, , "Emi|GHG|Energy|+|Supply (Mt CO2eq/yr)"] / 1000,
                          "Revenue|Government|Tax|Carbon|+|Supply (billion US$2005/yr)")
               )
  out <- mbind(out, setNames(out[, , "Revenue|Government|Tax|Carbon|+|Demand|Buildings (billion US$2005/yr)"]
                           + out[, , "Revenue|Government|Tax|Carbon|+|Demand|Transport (billion US$2005/yr)"]
                           + out[, , "Revenue|Government|Tax|Carbon|+|Demand|Industry (billion US$2005/yr)"]
                           + out[, , "Revenue|Government|Tax|Carbon|+|Supply (billion US$2005/yr)"],
                        "Revenue|Government|Tax|Carbon (billion US$2005/yr)")
               )

  #
  out <- mbind(out,setNames(abs(pm_taxCO2eq) * 1000 * 12/44, "Price|Carbon|Guardrail (US$2005/t CO2)"))
  CaptureBal_tmp <- new.magpie(getRegions(out), getYears(out), fill = NA)
  CaptureBal_tmp[,getYears(balcapture.m),] <- balcapture.m
  out <- mbind(out, setNames(CaptureBal_tmp / (budget.m+1e-10) / 3.66 * 1e3,
               "Price|Carbon|Captured (US$2005/t CO2)"))

  if (is.null(regionSubsetList$EUR)) {
    out <- mbind(out,setNames(pm_taxCO2eq * 1000 * 12/44, "Price|Carbon|EU-wide Regulation For All Sectors (US$2005/t CO2)"))
  } else {
    co2EUprice <- pm_taxCO2eq * 1000 * 12/44
    co2EUprice[getRegions(pm_taxCO2eq)[!getRegions(pm_taxCO2eq) %in% regionSubsetList$EUR],,] <- 0
    priceReg <- regionSubsetList$EUR[!regionSubsetList$EUR %in% c("DEU","FRA","EUC","EUW")][1] #select region to define EU price (excluding Germany and France)
    for (r in regionSubsetList$EUR){
      co2EUprice[r,,] <- as.vector(co2EUprice[priceReg,,])
    }
    out <- mbind(out,setNames(co2EUprice, "Price|Carbon|EU-wide Regulation For All Sectors (US$2005/t CO2)"))
  }

  if (!is.null(pm_taxemiMkt)) {
    out <- mbind(out,setNames(pm_taxemiMkt[,,"ETS"] * 1000 * 12/44, "Price|Carbon|ETS (US$2005/t CO2)"))
    out <- mbind(out,setNames(pm_taxemiMkt[,,"ES"] * 1000 * 12/44, "Price|Carbon|ESR (US$2005/t CO2)"))
  }

  if (!is.null(pm_taxCO2eqSCC)) {
      out <- mbind(out,setNames(abs(pm_taxCO2eqSCC) * 1000 * 12/44, "Price|Carbon|SCC (US$2005/t CO2)"))
  }

  out <- mbind(out,setNames(out[,,"Price|Carbon (US$2005/t CO2)"] * s_GWP_N2O, "Price|N2O (US$2005/t N2O)"))
  out <- mbind(out,setNames(out[,,"Price|Carbon (US$2005/t CO2)"] * s_GWP_CH4, "Price|CH4 (US$2005/t CH4)"))


  # adding extra variables for alternative carbon price aggregation weights
  out <- mbind(out,setNames(out[,,"Price|Carbon|Captured (US$2005/t CO2)"],
                            "Price|Carbon|Captured|AggregatedByGrossCO2 (US$2005/t CO2)"))
  out <- mbind(out,setNames(out[,,"Price|Carbon|EU-wide Regulation For All Sectors (US$2005/t CO2)"],
                            "Price|Carbon|EU-wide Regulation For All Sectors|AggregatedByGrossCO2 (US$2005/t CO2)"))
  out <- mbind(out,setNames(out[,,"Price|Carbon|Guardrail (US$2005/t CO2)"],
                            "Price|Carbon|Guardrail|AggregatedByGrossCO2 (US$2005/t CO2)"))
  out <- mbind(out,setNames(out[,,"Price|Carbon|SCC (US$2005/t CO2)"],
                            "Price|Carbon|SCC|AggregatedByGrossCO2 (US$2005/t CO2)"))


  # ---- mapping of weights for the variables for global aggregation ----
  int2ext <- c(
    "Price|Primary Energy|Biomass|Modern (US$2005/GJ)"                 = "PE|Biomass|Modern (EJ/yr)",
    "Price|Primary Energy|Oil (US$2005/GJ)"                            = "PE|Oil (EJ/yr)",
    "Price|Primary Energy|Gas (US$2005/GJ)"                            = "PE|Gas (EJ/yr)",
    "Price|Primary Energy|Coal (US$2005/GJ)"                           = "PE|Coal (EJ/yr)",
    "Price|Primary Energy|Nuclear (US$2005/GJ)"                        = "PE|Nuclear (EJ/yr)",
    "Price|Primary Energy|Biomass|1st Generation|Sugar and Starch (US$2005/GJ)" = "PE|Biomass|1st Generation (EJ/yr)",
    "Price|Primary Energy|Biomass|1st Generation|Oil-based (US$2005/GJ)" = "PE|Biomass|1st Generation (EJ/yr)",

    "Internal|Price|Biomass|Emulator presolve (US$2005/GJ)"            = "Primary Energy Production|Biomass|Energy Crops MAgPIE (EJ/yr)",
    "Internal|Price|Biomass|Emulator presolve shifted (US$2005/GJ)"    = "Primary Energy Production|Biomass|Energy Crops MAgPIE (EJ/yr)",
    "Internal|Price|Biomass|Emulator shifted (US$2005/GJ)"             = "Primary Energy Production|Biomass|Energy Crops (EJ/yr)",
    "Internal|Price|Biomass|MAgPIE (US$2005/GJ)"                       = "Primary Energy Production|Biomass|Energy Crops MAgPIE (EJ/yr)",
    "Internal|Price|Biomass|Bioenergy tax (US$2005/GJ)"                = "Primary Energy Production|Biomass|Energy Crops (EJ/yr)",
    "Price|N2O (US$2005/t N2O)"                                        = "Emi|N2O (kt N2O/yr)",
    "Price|CH4 (US$2005/t CH4)"                                        = "Emi|CH4 (Mt CH4/yr)",
    "Price|Secondary Energy|Electricity (US$2005/GJ)"                  = "SE|Electricity (EJ/yr)",
    "Price|Secondary Energy|Hydrogen (US$2005/GJ)"                     = "SE|Hydrogen (EJ/yr)",
    "Price|Secondary Energy|Heat (US$2005/GJ)"                         = "SE|Heat (EJ/yr)",
    "Price|Secondary Energy|Solids|Biomass (US$2005/GJ)"               = "SE|Solids|Biomass (EJ/yr)",
    "Price|Secondary Energy|Liquids|Biomass (US$2005/GJ)"              = "SE|Liquids|Biomass (EJ/yr)",
    "Price|Secondary Energy|Gases|Biomass (US$2005/GJ)"                = "SE|Gases|Biomass (EJ/yr)",
    "Price|Secondary Energy|Solids|Fossil (US$2005/GJ)"                = "SE|Solids|Coal (EJ/yr)",
    "Price|Secondary Energy|Liquids|Fossil (US$2005/GJ)"               = "SE|Liquids|Fossil|Oil (EJ/yr)",
    "Price|Secondary Energy|Gases|Fossil (US$2005/GJ)"                 = "SE|Gases|Fossil (EJ/yr)",
    "Price|Secondary Energy|Liquids|Hydrogen (US$2005/GJ)"             = "SE|Liquids|Hydrogen (EJ/yr)",
    "Price|Secondary Energy|Gases|Hydrogen (US$2005/GJ)"               = "SE|Gases|Hydrogen (EJ/yr)",
    "Price|Secondary Energy|Solids (US$2005/GJ)"                       = "SE|Solids (EJ/yr)",
    "Price|Secondary Energy|Liquids (US$2005/GJ)"                      = "SE|Liquids (EJ/yr)",
    "Price|Secondary Energy|Gases (US$2005/GJ)"                        = "SE|Gases (EJ/yr)",

    "Price|Carbon|ETS (US$2005/t CO2)"                                 = "Emi|GHG|ETS (Mt CO2eq/yr)",
    "Price|Carbon|ESR (US$2005/t CO2)"                                 = "Emi|GHG|ESR (Mt CO2eq/yr)",

    "Price|Carbon (US$2005/t CO2)"                                    = "FE (EJ/yr)",
    "Price|Carbon|Captured (US$2005/t CO2)"                           = "FE (EJ/yr)",
    "Price|Carbon|EU-wide Regulation For All Sectors (US$2005/t CO2)" = "FE (EJ/yr)",
    "Price|Carbon|Guardrail (US$2005/t CO2)"                          = "FE (EJ/yr)",
    "Price|Carbon|SCC (US$2005/t CO2)"                                = "FE (EJ/yr)",

    "Price|Carbon|Demand|Buildings (US$2005/t CO2)"                   = "FE (EJ/yr)",
    "Price|Carbon|Demand|Transport (US$2005/t CO2)"                   = "FE (EJ/yr)",
    "Price|Carbon|Demand|Industry (US$2005/t CO2)"                    = "FE (EJ/yr)",
    "Price|Carbon|Supply (US$2005/t CO2)"                             = "FE (EJ/yr)",

    "Price|Carbon|AggregatedByGrossCO2 (US$2005/t CO2)"               = "Emi|GHG|Gross|Energy (Mt CO2eq/yr)",
    "Price|Carbon|Captured|AggregatedByGrossCO2 (US$2005/t CO2)"      = "Emi|GHG|Gross|Energy (Mt CO2eq/yr)",
    "Price|Carbon|EU-wide Regulation For All Sectors|AggregatedByGrossCO2 (US$2005/t CO2)" = "Emi|GHG|Gross|Energy (Mt CO2eq/yr)",
    "Price|Carbon|Guardrail|AggregatedByGrossCO2 (US$2005/t CO2)"     = "Emi|GHG|Gross|Energy (Mt CO2eq/yr)",
    "Price|Carbon|SCC|AggregatedByGrossCO2 (US$2005/t CO2)"           = "Emi|GHG|Gross|Energy (Mt CO2eq/yr)"
    )

  if (!is.null(esm2macro.m)) {
    int2ext <- c(int2ext,
                 "Price|Energy Service|Transport LDV (US$2005/GJ)"         = "CES_input|fepet (EJ/yr)",  ## TODO: check units
                 "Price|Energy Service|Transport nonLDV (US$2005/GJ)"      = "CES_input|fedie (EJ/yr)"  ## TODO: check units
    )
  }

  ## weights definition for region aggregation
  int2ext <- c(int2ext,

               ## transport prices
               "Price|Final Energy|Transport|Electricity (US$2005/GJ)"       = "FE|Transport|Electricity (EJ/yr)",
               "Price|Final Energy|Transport|Liquids (US$2005/GJ)"       = "FE|Transport|Liquids (EJ/yr)",
               "Price|Final Energy|Transport|Hydrogen (US$2005/GJ)"       = "FE|Transport|Hydrogen (EJ/yr)",

               ## buildings prices
               "Price|Final Energy|Buildings|Electricity (US$2005/GJ)"       = "FE|Buildings|Electricity (EJ/yr)",
               "Price|Final Energy|Buildings|Liquids (US$2005/GJ)"       = "FE|Buildings|Liquids (EJ/yr)",
               "Price|Final Energy|Buildings|Gases (US$2005/GJ)"       = "FE|Buildings|Gases (EJ/yr)",
               "Price|Final Energy|Buildings|Hydrogen (US$2005/GJ)"       = "FE|Buildings|Hydrogen (EJ/yr)",
               "Price|Final Energy|Buildings|Heat (US$2005/GJ)"       = "FE|Buildings|Heat (EJ/yr)",
               "Price|Final Energy|Buildings|Solids (US$2005/GJ)"       = "FE|Buildings|Solids (EJ/yr)",

               ## industry prices
               "Price|Final Energy|Industry|Electricity (US$2005/GJ)"       = "FE|Industry|Electricity (EJ/yr)",
               "Price|Final Energy|Industry|Liquids (US$2005/GJ)"       = "FE|Industry|Liquids (EJ/yr)",
               "Price|Final Energy|Industry|Gases (US$2005/GJ)"       = "FE|Industry|Gases (EJ/yr)",
               "Price|Final Energy|Industry|Hydrogen (US$2005/GJ)"       = "FE|Industry|Hydrogen (EJ/yr)",
               "Price|Final Energy|Industry|Heat (US$2005/GJ)"       = "FE|Industry|Heat (EJ/yr)",
               "Price|Final Energy|Industry|Solids (US$2005/GJ)"       = "FE|Industry|Solids (EJ/yr)"
               )



  # transport-specific mappings depending on realization

  if (module2realisation["transport",2] == "complex") {
    int2ext <- c(int2ext,
                 "Price|Final Energy|Transport|Liquids|HDV (US$2005/GJ)"       = "FE|Transport|non-LDV|Liquids (EJ/yr)",
                 "Price|Final Energy|Transport|Liquids|LDV (US$2005/GJ)"       = "FE|Transport|LDV|Liquids (EJ/yr)")
  } else if (module2realisation["transport",2] == "edge_esm") {
    int2ext <- c(int2ext,
                 "Price|Final Energy|Transport|Liquids|HDV (US$2005/GJ)"       = "FE|Transport|Diesel Liquids (EJ/yr)",
                 "Price|Final Energy|Transport|Liquids|LDV (US$2005/GJ)"       = "FE|Transport|Pass|Liquids (EJ/yr)",
                 "Price|Final Energy|Transport|Gases (US$2005/GJ)"       = "FE|Transport|Gases (EJ/yr)")
  }



  ## moving averages
  avgs <- grep("Moving Avg", getNames(out), value=TRUE)
  ## exclude detailed FE prices from global aggregation
  avgs <- setdiff(avgs, grep("Total LCOE|Transport and Distribution|Other Taxes|Fuel Cost|Carbon Price Component", avgs, value = TRUE))
  int2ext <- c(int2ext, stats::setNames(int2ext[gsub("\\|Moving Avg", "", avgs)], avgs))

  ## bind to output object
  if(is.null(output)){
    output <- reportPE(gdx,regionSubsetList = regionSubsetList,t = t)
    output <- mbind(output,reportSE(gdx,regionSubsetList = regionSubsetList,t = t))
    output <- mbind(output,FE_data)
    output <- mbind(output,Emi_data)
    output <- mbind(output,reportExtraction(gdx,regionSubsetList = regionSubsetList,t = t))
    output <- mbind(output,reportMacroEconomy(gdx,regionSubsetList = regionSubsetList,t = t)[,getYears(output),])
  }

  output[is.na(output)] <- 0  # substitute na by 0

  ## delete "+" and "++" from variable names
  output <- deletePlus(output)


  # # ---- internal price variables used for modelg diagnostics -----

  # # CES prices and CES markup cost





  o01_CESderivatives <- readGDX(gdx, "o01_CESderivatives", restore_zeros = T, react = "silent")

  if (!is.null(o01_CESderivatives)) {


  o01_CESderivatives <- o01_CESderivatives[,YearsFrom2005,]


  # CES price is derivative of GDP with respect to production factor (CES node)
  # temporay: only report CES prices of primary production factors (bottom-most CES nodes) for buildings and industry for now to not oversize the reporting
  # TODO: generate MIF without internal variables as standard such that more internal variables can be added here

  ppfen_industry_dyn37 <- readGDX(gdx, "ppfen_industry_dyn37")
  ppfen_buildings_dyn36 <- readGDX(gdx, "ppfen_buildings_dyn36")
  ppfen <- c(ppfen_industry_dyn37, ppfen_buildings_dyn36)


  # CES Prices

  # choose derivative of GDP (inco) with respect to input
  ces_price <- collapseDim(mselect(o01_CESderivatives, all_in = "inco", all_in1 = ppfen))
  # variable names
  ces_price <- setNames(ces_price, paste0("Internal|Price|CES|",getNames(ces_price)," (tr US$2005/input unit)"))

  # CES Markup Cost
  p37_CESMkup <- readGDX(gdx, "p37_CESMkup") # markup in industry
  p36_CESMkup <- readGDX(gdx, "p36_CESMkup") # markup in buildings


  CESMkup <- mbind(
    mselect(p36_CESMkup[,YearsFrom2005,], all_in = ppfen_buildings_dyn36),
    mselect(p37_CESMkup[,YearsFrom2005,], all_in = ppfen_industry_dyn37))

  CESMkup <- setNames( CESMkup, paste0("Internal|CES Markup Cost|",getNames(CESMkup)," (tr US$2005/input unit)"))


  out <- mbind(out, ces_price, CESMkup)

  }

  # add global prices
  map <- data.frame(region=getRegions(out),world="GLO",stringsAsFactors=FALSE)
  tmp_GLO <- new.magpie("GLO",getYears(out),getNames(out),fill=0)

  for (i2e in names(int2ext)){
    tmp_GLO["GLO",,i2e] <- speed_aggregate(out[,,i2e],map,weight=output[map$region,,int2ext[i2e]])
    for(t in getYears(out)){
      if(all(output[map$region,t,int2ext[i2e]]==0)){
        tmp_GLO["GLO",t,i2e] <- NA
      }
    }
  }
  out <- mbind(out,tmp_GLO)

  # add other region aggregations
  if (!is.null(regionSubsetList)){
    tmp_RegAgg <- new.magpie(names(regionSubsetList),getYears(out),getNames(out),fill=0)
    for(region in names(regionSubsetList)){
      tmp_RegAgg_ie2 <- do.call("mbind",lapply(names(int2ext), function(i2e) {
        map <- data.frame(region=regionSubsetList[[region]],parentRegion=region,stringsAsFactors=FALSE)
        result <- speed_aggregate(out[regionSubsetList[[region]],,i2e],map,weight=output[regionSubsetList[[region]],,int2ext[i2e]])
        getItems(result, dim = 1) <- region
        for(t in getYears(out)){
          if(all(output[regionSubsetList[[region]],t,int2ext[i2e]]==0)){
            result[region,t,i2e] <- NA
          }
        }
        return(result)
      }))
      tmp_RegAgg[region,,names(int2ext)] <- tmp_RegAgg_ie2[region,,names(int2ext)]
    }
    out <- mbind(out, tmp_RegAgg)
  }

  out[is.na(out)] <- 0  # out is NA if weight is zero for all regions within the GLO or the specific region aggregation. Therefore, we replace all NAs with zeros.

  # prices that are same for all regions, including GLO
  glob_price <- new.magpie(getRegions(out),getYears(out),fill=0)
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"peur"]*1000
  out <- mbind(out,setNames(glob_price,                             "PVP1|Uranium (billionDpktU)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"peoil"]*1000
  out <- mbind(out,setNames(glob_price,                             "PVP1|Oil (billionDpTWyr)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"pegas"]*1000
  out <- mbind(out,setNames(glob_price,                             "PVP1|Gas (billionDpTWyr)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"pecoal"]*1000
  out <- mbind(out,setNames(glob_price,                             "PVP1|Coal (billionDpTWyr)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"pebiolc"]*1000
  out <- mbind(out,setNames(glob_price,                             "PVP1|Biomass (billionDpTWyr)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"good"]*1000
  out <- mbind(out,setNames(glob_price,                             "PVP2|Good ()"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"perm"]
  out <- mbind(out,setNames(glob_price,                             "PVP3|Permit ()"))

  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"peur"]/pm_pvp[,,"good"] * tdptwyr2dpgj
  out <- mbind(out,setNames(glob_price,                                       "Price|Uranium|World Market (US$2005/GJ)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"peoil"]/pm_pvp[,,"good"] * tdptwyr2dpgj
  out <- mbind(out,setNames(glob_price,                                       "Price|Oil|World Market (US$2005/GJ)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"pegas"]/pm_pvp[,,"good"] * tdptwyr2dpgj
  out <- mbind(out,setNames(glob_price,                                       "Price|Gas|World Market (US$2005/GJ)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"pecoal"]/pm_pvp[,,"good"] * tdptwyr2dpgj
  out <- mbind(out,setNames(glob_price,                                       "Price|Coal|World Market (US$2005/GJ)"))
  for(i in getRegions(out)) glob_price[i,,] <- pm_pvp[,,"pebiolc"]/pm_pvp[,,"good"] * tdptwyr2dpgj
  out <- mbind(out,setNames(glob_price,                                       "Price|Biomass|World Market (US$2005/GJ)"))

  ## special global prices

  ## not meaningful global prices set to NA
  out["GLO",,"Internal|Price|Biomass|Shiftfactor ()"] <- NA

  if (!is.null(regionSubsetList$EUR))
    out["EUR",,"Price|Carbon|EU-wide Regulation For All Sectors (US$2005/t CO2)"] <- as.vector(co2EUprice[priceReg,,])

  ## not meaningful region aggregation prices set to NA
  if (!is.null(regionSubsetList)){
    for(region in names(regionSubsetList)){
      out[region,,"Internal|Price|Biomass|Shiftfactor ()"] <- NA
    }
  }

  # comment out this section for now as errors, debug this section if needed
  # # ---- debug information for industry/subsectors ----
  # if ('subsectors' == indu_mod & !is.null(q37_limit_secondary_steel_share.m)) {
  #
  #   t <- getYears(budget.m)
  #
  #   .x <- q37_limit_secondary_steel_share.m[, t,] / budget.m
  #   .x <- mbind(.x, calc_regionSubset_sums(.x, regionSubsetList))
  #
  #
  #   tmp2 <- mbind(
  #     # fake some GLO data
  #     setNames(
  #       mbind(.x, dimSums(.x * NA, dim = 1)),
  #       'Debug|Industry|Secondary Steel Premium (US$2005)'),
  #
  #     mbind(
  #       lapply(
  #         list(
  #           c('ue_industry',        '',                 'arbitrary unit', 1),
  #           c('ue_cement',          '|Cement',          't cement',       1e3),
  #           c('ue_chemicals',       '|Chemicals',       'arbitrary unit', 1),
  #           c('ue_steel',           '|Steel',           't Steel',        1e3),
  #           c('ue_steel_primary',   '|Steel|Primary',   't Steel',        1e3),
  #           c('ue_steel_secondary', '|Steel|Secondary', 't Steel',        1e3),
  #           c('ue_otherInd',        '|other',           'arbitrary unit', 1)),
  #         function(x) {
  #           setNames(
  #             ( out[,,paste0('Price|CES_input|', x[1], ' ('), pmatch = 'left']
  #               * as.numeric(x[4])
  #             ),
  #             paste0('Debug|Price|Industry', x[2], ' (US$2005/', x[3], ')'))
  #         })
  #     )
  #   )
  #
  #   out <- mbind(out, tmp2)
  # }

  return(out)
}
