#' Add SDP variables to mif, used in convGDX2MIF.R for the reporting
#' 

#' 
#' 
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' 
#' @return MAgPIE object - contains the SDP
#' @author Sebastian Rauner
#' @seealso \code{\link{convGDX2MIF}}
#' @examples
#' 
#' \dontrun{reportSDPVariables(output)}
#' 
#' @export

#' 
#' 
#' @importFrom magclass setNames names mbind mselect 
#' @importFrom dplyr filter


reportSDPVariables <- function(output=NULL) {
  
  
  #from "calcSDPTransport.R"
  output <- addUEperCapForTransport(output)
  
  #from "calcSDPIndustry.R"
  output <- addIndustry_UE_from_FE(output)
  
  #buildings need a sleeker way to calculate UE
  
  #from "calcSDPBuildings.R"
  #output <- addBuildings(output)
  
  
  # UE buildings in still missing, see above
  #from "calcSDPIntensity.R"
  #output <- addIntensityUE(output)
  
  
  return(output)
}
